creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: D52B8F3F106D2AC2C72D5B1BFA1E7946FB4F37A5
#    ,ANOTHER_D52B8F3F106D2AC2C72D5B1BFA1E7946FB4F37A5
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: D52B8F3F106D2AC2C72D5B1BFA1E7946FB4F37A5
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_D52B8F3F106D2AC2C72D5B1BFA1E7946FB4F37A5
