creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 02E9F42D66181F31C65AE49A2BF4679927DF680E
#    ,ANOTHER_02E9F42D66181F31C65AE49A2BF4679927DF680E
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 02E9F42D66181F31C65AE49A2BF4679927DF680E
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_02E9F42D66181F31C65AE49A2BF4679927DF680E
