creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 73B007DF5650B961DBA116D9F5674D5F7E74230F
#    ,ANOTHER_73B007DF5650B961DBA116D9F5674D5F7E74230F
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 73B007DF5650B961DBA116D9F5674D5F7E74230F
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_73B007DF5650B961DBA116D9F5674D5F7E74230F
