creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: EF12472A7A0B1B79F4596C3B072AC771D2C683A1
#    ,ANOTHER_EF12472A7A0B1B79F4596C3B072AC771D2C683A1
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: EF12472A7A0B1B79F4596C3B072AC771D2C683A1
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_EF12472A7A0B1B79F4596C3B072AC771D2C683A1
