creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 20DD7F9000971B9AB04FA7360ACC8FFAED52CC29
#    ,ANOTHER_20DD7F9000971B9AB04FA7360ACC8FFAED52CC29
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 20DD7F9000971B9AB04FA7360ACC8FFAED52CC29
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_20DD7F9000971B9AB04FA7360ACC8FFAED52CC29
