creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: F9E3073B0F4A7B62F6B8372F47138DAB81015967
#    ,ANOTHER_F9E3073B0F4A7B62F6B8372F47138DAB81015967
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: F9E3073B0F4A7B62F6B8372F47138DAB81015967
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_F9E3073B0F4A7B62F6B8372F47138DAB81015967
