creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: D2CE74FDA83ACBBDD05DCCC8A0958A85A8CE8F24
#    ,ANOTHER_D2CE74FDA83ACBBDD05DCCC8A0958A85A8CE8F24
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: D2CE74FDA83ACBBDD05DCCC8A0958A85A8CE8F24
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_D2CE74FDA83ACBBDD05DCCC8A0958A85A8CE8F24
