creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 48B54B51C431AF6A9C199884E7AADF2FDB4597BD
#    ,ANOTHER_48B54B51C431AF6A9C199884E7AADF2FDB4597BD
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 48B54B51C431AF6A9C199884E7AADF2FDB4597BD
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_48B54B51C431AF6A9C199884E7AADF2FDB4597BD
