creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 2938F9AFD205AA342698ABDD63D28CAC311B71F7
#    ,ANOTHER_2938F9AFD205AA342698ABDD63D28CAC311B71F7
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 2938F9AFD205AA342698ABDD63D28CAC311B71F7
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_2938F9AFD205AA342698ABDD63D28CAC311B71F7
