creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: E6AB7AD389465E358DAB132F8FF8A435C3B8D0DB
#    ,ANOTHER_E6AB7AD389465E358DAB132F8FF8A435C3B8D0DB
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: E6AB7AD389465E358DAB132F8FF8A435C3B8D0DB
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_E6AB7AD389465E358DAB132F8FF8A435C3B8D0DB
