creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: D6D0B43671D8EE79240663BC4A62CAA5DE46D9CC
#    ,ANOTHER_D6D0B43671D8EE79240663BC4A62CAA5DE46D9CC
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: D6D0B43671D8EE79240663BC4A62CAA5DE46D9CC
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_D6D0B43671D8EE79240663BC4A62CAA5DE46D9CC
