creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 7FB001E77860BF60346DCD3B1E3F5A176D4B858C
#    ,ANOTHER_7FB001E77860BF60346DCD3B1E3F5A176D4B858C
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 7FB001E77860BF60346DCD3B1E3F5A176D4B858C
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_7FB001E77860BF60346DCD3B1E3F5A176D4B858C
