creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: DD638A6D377680C6ABEAAC45320BF59DE48B26E9
#    ,ANOTHER_DD638A6D377680C6ABEAAC45320BF59DE48B26E9
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: DD638A6D377680C6ABEAAC45320BF59DE48B26E9
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_DD638A6D377680C6ABEAAC45320BF59DE48B26E9
