creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 4D5FD8B13291F7C22A858F4C4C9CA133355D0F58
#    ,ANOTHER_4D5FD8B13291F7C22A858F4C4C9CA133355D0F58
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 4D5FD8B13291F7C22A858F4C4C9CA133355D0F58
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_4D5FD8B13291F7C22A858F4C4C9CA133355D0F58
