creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 4722F7B0F85335FAEEB4F5752406E3459CA8B3AA
#    ,ANOTHER_4722F7B0F85335FAEEB4F5752406E3459CA8B3AA
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 4722F7B0F85335FAEEB4F5752406E3459CA8B3AA
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_4722F7B0F85335FAEEB4F5752406E3459CA8B3AA
