creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 7F19BDCEBB6BFD7C1FFCCE89BB09A794788CA8FD
#    ,ANOTHER_7F19BDCEBB6BFD7C1FFCCE89BB09A794788CA8FD
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 7F19BDCEBB6BFD7C1FFCCE89BB09A794788CA8FD
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_7F19BDCEBB6BFD7C1FFCCE89BB09A794788CA8FD
