creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 8867F4B8E99FAFB6B8511152C2A682847A6267E4
#    ,ANOTHER_8867F4B8E99FAFB6B8511152C2A682847A6267E4
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 8867F4B8E99FAFB6B8511152C2A682847A6267E4
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_8867F4B8E99FAFB6B8511152C2A682847A6267E4
