creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 2397FB91E3F6074BFF1C9DE0C0E397DB01F40AEF
#    ,ANOTHER_2397FB91E3F6074BFF1C9DE0C0E397DB01F40AEF
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 2397FB91E3F6074BFF1C9DE0C0E397DB01F40AEF
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_2397FB91E3F6074BFF1C9DE0C0E397DB01F40AEF
