creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 63C44B9CBDD7A7E84A5EB6CFC4415F2DF9D4697A
#    ,ANOTHER_63C44B9CBDD7A7E84A5EB6CFC4415F2DF9D4697A
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 63C44B9CBDD7A7E84A5EB6CFC4415F2DF9D4697A
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_63C44B9CBDD7A7E84A5EB6CFC4415F2DF9D4697A
