creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: ED2E140E26FEAF83CD5570FB989780FBBDBC7DC7
#    ,ANOTHER_ED2E140E26FEAF83CD5570FB989780FBBDBC7DC7
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ED2E140E26FEAF83CD5570FB989780FBBDBC7DC7
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_ED2E140E26FEAF83CD5570FB989780FBBDBC7DC7
