creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 422BA9F43D03BBB8CB0E67F01B31616145B86FDD
#    ,ANOTHER_422BA9F43D03BBB8CB0E67F01B31616145B86FDD
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 422BA9F43D03BBB8CB0E67F01B31616145B86FDD
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_422BA9F43D03BBB8CB0E67F01B31616145B86FDD
