creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: D385BBE9E843BD2B57B8908F828F7B78C1C224BE
#    ,ANOTHER_D385BBE9E843BD2B57B8908F828F7B78C1C224BE
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: D385BBE9E843BD2B57B8908F828F7B78C1C224BE
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_D385BBE9E843BD2B57B8908F828F7B78C1C224BE
