creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 2B89F49C07BBDDDD9CE70E3C57B2B31FE9C7BEC9
#    ,ANOTHER_2B89F49C07BBDDDD9CE70E3C57B2B31FE9C7BEC9
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 2B89F49C07BBDDDD9CE70E3C57B2B31FE9C7BEC9
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_2B89F49C07BBDDDD9CE70E3C57B2B31FE9C7BEC9
