creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: C794880B8246F2C5C04B56035B9450E678024DAE
#    ,ANOTHER_C794880B8246F2C5C04B56035B9450E678024DAE
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: C794880B8246F2C5C04B56035B9450E678024DAE
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_C794880B8246F2C5C04B56035B9450E678024DAE
