creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 3333B15D629FC9F671D1875C433ACA89EF65B447
#    ,ANOTHER_3333B15D629FC9F671D1875C433ACA89EF65B447
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 3333B15D629FC9F671D1875C433ACA89EF65B447
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_3333B15D629FC9F671D1875C433ACA89EF65B447
