creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: AAD5DC21D955BA1EA28C8E8E1E87E00BA3C9CC57
#    ,ANOTHER_AAD5DC21D955BA1EA28C8E8E1E87E00BA3C9CC57
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: AAD5DC21D955BA1EA28C8E8E1E87E00BA3C9CC57
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_AAD5DC21D955BA1EA28C8E8E1E87E00BA3C9CC57
