creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 74E2738960B8A6B37E72783C3F28FBA1B4CEB71C
#    ,ANOTHER_74E2738960B8A6B37E72783C3F28FBA1B4CEB71C
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 74E2738960B8A6B37E72783C3F28FBA1B4CEB71C
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_74E2738960B8A6B37E72783C3F28FBA1B4CEB71C
