creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 3C4BB5CD12A16943FD7E641E6ADE3502E3C43E1D
#    ,ANOTHER_3C4BB5CD12A16943FD7E641E6ADE3502E3C43E1D
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 3C4BB5CD12A16943FD7E641E6ADE3502E3C43E1D
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_3C4BB5CD12A16943FD7E641E6ADE3502E3C43E1D
