creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 8DBBEE96BEC8050FC35433D577D10A40D233E38D
#    ,ANOTHER_8DBBEE96BEC8050FC35433D577D10A40D233E38D
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 8DBBEE96BEC8050FC35433D577D10A40D233E38D
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_8DBBEE96BEC8050FC35433D577D10A40D233E38D
