creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: F32B4638269986AB7F0325DDE06A7AF9446AB9AC
#    ,ANOTHER_F32B4638269986AB7F0325DDE06A7AF9446AB9AC
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: F32B4638269986AB7F0325DDE06A7AF9446AB9AC
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_F32B4638269986AB7F0325DDE06A7AF9446AB9AC
