creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: CC2EF0BB15B64F892CF028EB073507CF8C1208B3
#    ,ANOTHER_CC2EF0BB15B64F892CF028EB073507CF8C1208B3
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: CC2EF0BB15B64F892CF028EB073507CF8C1208B3
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_CC2EF0BB15B64F892CF028EB073507CF8C1208B3
