creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 4BC384ACDA2C214C0FD138A7C6153DEAFD7BFB24
#    ,ANOTHER_4BC384ACDA2C214C0FD138A7C6153DEAFD7BFB24
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 4BC384ACDA2C214C0FD138A7C6153DEAFD7BFB24
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_4BC384ACDA2C214C0FD138A7C6153DEAFD7BFB24
