creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 60859321D9A7E2399B5DE9203117A58DE49558A4
#    ,ANOTHER_60859321D9A7E2399B5DE9203117A58DE49558A4
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 60859321D9A7E2399B5DE9203117A58DE49558A4
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_60859321D9A7E2399B5DE9203117A58DE49558A4
