creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 05785421216D5CC376A68F1C39B9221808DF165A
#    ,ANOTHER_05785421216D5CC376A68F1C39B9221808DF165A
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 05785421216D5CC376A68F1C39B9221808DF165A
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_05785421216D5CC376A68F1C39B9221808DF165A
