creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 62E579CA9D5A78B6AA76F90C78343C3DEA6C7F49
#    ,ANOTHER_62E579CA9D5A78B6AA76F90C78343C3DEA6C7F49
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 62E579CA9D5A78B6AA76F90C78343C3DEA6C7F49
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_62E579CA9D5A78B6AA76F90C78343C3DEA6C7F49
