creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: F12A741D703B30370E18A0C32E1CCEE71E5D7D96
#    ,ANOTHER_F12A741D703B30370E18A0C32E1CCEE71E5D7D96
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: F12A741D703B30370E18A0C32E1CCEE71E5D7D96
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_F12A741D703B30370E18A0C32E1CCEE71E5D7D96
