creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 4B6E256F91F85C7847D95543B9FD3C702CD9649D
#    ,ANOTHER_4B6E256F91F85C7847D95543B9FD3C702CD9649D
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 4B6E256F91F85C7847D95543B9FD3C702CD9649D
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_4B6E256F91F85C7847D95543B9FD3C702CD9649D
