creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 1C776ADAB634E50876A4FDC30D3A0A78099DB0D2
#    ,ANOTHER_1C776ADAB634E50876A4FDC30D3A0A78099DB0D2
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 1C776ADAB634E50876A4FDC30D3A0A78099DB0D2
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_1C776ADAB634E50876A4FDC30D3A0A78099DB0D2
