creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 3225BEEF514104E09F4C58211000E2B05AA93FBA
#    ,ANOTHER_3225BEEF514104E09F4C58211000E2B05AA93FBA
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 3225BEEF514104E09F4C58211000E2B05AA93FBA
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_3225BEEF514104E09F4C58211000E2B05AA93FBA
