creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 09FC8C647B31F688BD0E83FA04DA9DD097E36798
#    ,ANOTHER_09FC8C647B31F688BD0E83FA04DA9DD097E36798
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 09FC8C647B31F688BD0E83FA04DA9DD097E36798
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_09FC8C647B31F688BD0E83FA04DA9DD097E36798
