creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: B67DC3E37B9EA55195AC0E090550497FD25582B2
#    ,ANOTHER_B67DC3E37B9EA55195AC0E090550497FD25582B2
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: B67DC3E37B9EA55195AC0E090550497FD25582B2
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_B67DC3E37B9EA55195AC0E090550497FD25582B2
