creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: E98C504669C1F17C9E41968690A0233055873121
#    ,ANOTHER_E98C504669C1F17C9E41968690A0233055873121
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: E98C504669C1F17C9E41968690A0233055873121
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_E98C504669C1F17C9E41968690A0233055873121
