creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: DE3EEE3B84115B7CF81897700E8F8A3856EE5BEB
#    ,ANOTHER_DE3EEE3B84115B7CF81897700E8F8A3856EE5BEB
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: DE3EEE3B84115B7CF81897700E8F8A3856EE5BEB
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_DE3EEE3B84115B7CF81897700E8F8A3856EE5BEB
