creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 1BF01269A45DB0F6C80ECA563D71B904CE4D85B5
#    ,ANOTHER_1BF01269A45DB0F6C80ECA563D71B904CE4D85B5
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 1BF01269A45DB0F6C80ECA563D71B904CE4D85B5
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_1BF01269A45DB0F6C80ECA563D71B904CE4D85B5
