creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 02523C633D5B3DA637275885DDBF00F747D23864
#    ,ANOTHER_02523C633D5B3DA637275885DDBF00F747D23864
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 02523C633D5B3DA637275885DDBF00F747D23864
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_02523C633D5B3DA637275885DDBF00F747D23864
