creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: E6423BA6F5770765CCB23639740DCDB353C49806
#    ,ANOTHER_E6423BA6F5770765CCB23639740DCDB353C49806
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: E6423BA6F5770765CCB23639740DCDB353C49806
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_E6423BA6F5770765CCB23639740DCDB353C49806
