creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 186842EB906B8C99C48B77F94E6ED9F80CBCD71D
#    ,ANOTHER_186842EB906B8C99C48B77F94E6ED9F80CBCD71D
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 186842EB906B8C99C48B77F94E6ED9F80CBCD71D
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_186842EB906B8C99C48B77F94E6ED9F80CBCD71D
