creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 2219E1B3607B9FD7499D4A8DFF36861ACAE1EF47
#    ,ANOTHER_2219E1B3607B9FD7499D4A8DFF36861ACAE1EF47
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 2219E1B3607B9FD7499D4A8DFF36861ACAE1EF47
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_2219E1B3607B9FD7499D4A8DFF36861ACAE1EF47
