creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 8EBBBF7DEE0167EA9E27B43036852B616BC17467
#    ,ANOTHER_8EBBBF7DEE0167EA9E27B43036852B616BC17467
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 8EBBBF7DEE0167EA9E27B43036852B616BC17467
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_8EBBBF7DEE0167EA9E27B43036852B616BC17467
