creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 4FB16A8A7805C2BA5D22551F4F363EBF1C39F3C3
#    ,ANOTHER_4FB16A8A7805C2BA5D22551F4F363EBF1C39F3C3
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 4FB16A8A7805C2BA5D22551F4F363EBF1C39F3C3
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_4FB16A8A7805C2BA5D22551F4F363EBF1C39F3C3
