creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 0DA051A11F759C7037D0297A494897BF3D123CE3
#    ,ANOTHER_0DA051A11F759C7037D0297A494897BF3D123CE3
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 0DA051A11F759C7037D0297A494897BF3D123CE3
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_0DA051A11F759C7037D0297A494897BF3D123CE3
