creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 3C548E4EDCF003D94E1BE45E7234CA9F6B132921
#    ,ANOTHER_3C548E4EDCF003D94E1BE45E7234CA9F6B132921
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 3C548E4EDCF003D94E1BE45E7234CA9F6B132921
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_3C548E4EDCF003D94E1BE45E7234CA9F6B132921
