creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 1695BDFC64BEEB5773D09D4D9A624DDE7AD026CB
#    ,ANOTHER_1695BDFC64BEEB5773D09D4D9A624DDE7AD026CB
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 1695BDFC64BEEB5773D09D4D9A624DDE7AD026CB
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_1695BDFC64BEEB5773D09D4D9A624DDE7AD026CB
