creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 9322AEED952E25BA8F1CC66F6CA29818E7AE1F0F
#    ,ANOTHER_9322AEED952E25BA8F1CC66F6CA29818E7AE1F0F
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 9322AEED952E25BA8F1CC66F6CA29818E7AE1F0F
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_9322AEED952E25BA8F1CC66F6CA29818E7AE1F0F
