creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: CC024EEEA2CB6DD606E737C3D15EED89E0132A8C
#    ,ANOTHER_CC024EEEA2CB6DD606E737C3D15EED89E0132A8C
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: CC024EEEA2CB6DD606E737C3D15EED89E0132A8C
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_CC024EEEA2CB6DD606E737C3D15EED89E0132A8C
