creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 1CE2A3387F380CFF251A805B5CD907CA9342EE46
#    ,ANOTHER_1CE2A3387F380CFF251A805B5CD907CA9342EE46
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 1CE2A3387F380CFF251A805B5CD907CA9342EE46
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_1CE2A3387F380CFF251A805B5CD907CA9342EE46
