creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 53A45E7B429BD61830CF2AF40599873D75D86AFB
#    ,ANOTHER_53A45E7B429BD61830CF2AF40599873D75D86AFB
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 53A45E7B429BD61830CF2AF40599873D75D86AFB
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_53A45E7B429BD61830CF2AF40599873D75D86AFB
