creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 1620919B74CFFA84295667378733247F28AFE256
#    ,ANOTHER_1620919B74CFFA84295667378733247F28AFE256
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 1620919B74CFFA84295667378733247F28AFE256
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_1620919B74CFFA84295667378733247F28AFE256
