creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: BE85C38D3C84FB311856C755EDE7260FF8755B98
#    ,ANOTHER_BE85C38D3C84FB311856C755EDE7260FF8755B98
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: BE85C38D3C84FB311856C755EDE7260FF8755B98
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_BE85C38D3C84FB311856C755EDE7260FF8755B98
