creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 344F4519FAF11A57806906CDF4C71F623BE118F5
#    ,ANOTHER_344F4519FAF11A57806906CDF4C71F623BE118F5
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 344F4519FAF11A57806906CDF4C71F623BE118F5
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_344F4519FAF11A57806906CDF4C71F623BE118F5
