creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: C1267A3F73F2C602426A92E19C8B62C5A7E706D4
#    ,ANOTHER_C1267A3F73F2C602426A92E19C8B62C5A7E706D4
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: C1267A3F73F2C602426A92E19C8B62C5A7E706D4
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_C1267A3F73F2C602426A92E19C8B62C5A7E706D4
