creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 6D9ACD2B8464A3963C5491DBC28E6ADC70978CFC
#    ,ANOTHER_6D9ACD2B8464A3963C5491DBC28E6ADC70978CFC
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 6D9ACD2B8464A3963C5491DBC28E6ADC70978CFC
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_6D9ACD2B8464A3963C5491DBC28E6ADC70978CFC
