creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 3A70D5177284887695716CB707A358FDD1D36476
#    ,ANOTHER_3A70D5177284887695716CB707A358FDD1D36476
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 3A70D5177284887695716CB707A358FDD1D36476
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_3A70D5177284887695716CB707A358FDD1D36476
