creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 2E2F29A21CD69ACA25D8A218FDB3ABAC62E8C4A1
#    ,ANOTHER_2E2F29A21CD69ACA25D8A218FDB3ABAC62E8C4A1
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 2E2F29A21CD69ACA25D8A218FDB3ABAC62E8C4A1
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_2E2F29A21CD69ACA25D8A218FDB3ABAC62E8C4A1
