creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: FCC297E679CFBB192F01EED286AB465DB17DC205
#    ,ANOTHER_FCC297E679CFBB192F01EED286AB465DB17DC205
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: FCC297E679CFBB192F01EED286AB465DB17DC205
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_FCC297E679CFBB192F01EED286AB465DB17DC205
