creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: C8EBB7CB206927356151D4CC41A681617040F0FC
#    ,ANOTHER_C8EBB7CB206927356151D4CC41A681617040F0FC
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: C8EBB7CB206927356151D4CC41A681617040F0FC
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_C8EBB7CB206927356151D4CC41A681617040F0FC
