creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 5D7D7DDD5703316699C82D2D163D4FDEC11242C5
#    ,ANOTHER_5D7D7DDD5703316699C82D2D163D4FDEC11242C5
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 5D7D7DDD5703316699C82D2D163D4FDEC11242C5
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_5D7D7DDD5703316699C82D2D163D4FDEC11242C5
