creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 50D92E7D069BED5E6317A77F6921D53880DA3C64
#    ,ANOTHER_50D92E7D069BED5E6317A77F6921D53880DA3C64
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 50D92E7D069BED5E6317A77F6921D53880DA3C64
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_50D92E7D069BED5E6317A77F6921D53880DA3C64
