creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 922DCE6C0FDA09AC3D776AAD19E89E783B862CA4
#    ,ANOTHER_922DCE6C0FDA09AC3D776AAD19E89E783B862CA4
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 922DCE6C0FDA09AC3D776AAD19E89E783B862CA4
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_922DCE6C0FDA09AC3D776AAD19E89E783B862CA4
