creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: E20408FE975A50629CA3B8337934183CE37E53C1
#    ,ANOTHER_E20408FE975A50629CA3B8337934183CE37E53C1
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: E20408FE975A50629CA3B8337934183CE37E53C1
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_E20408FE975A50629CA3B8337934183CE37E53C1
