creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 002290CB07FC5B2E879DD9DB06C3CBE6E288D58A
#    ,ANOTHER_002290CB07FC5B2E879DD9DB06C3CBE6E288D58A
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 002290CB07FC5B2E879DD9DB06C3CBE6E288D58A
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_002290CB07FC5B2E879DD9DB06C3CBE6E288D58A
