creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: C71B2D27A813BA1CA96B5A46E2F0559067592861
#    ,ANOTHER_C71B2D27A813BA1CA96B5A46E2F0559067592861
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: C71B2D27A813BA1CA96B5A46E2F0559067592861
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_C71B2D27A813BA1CA96B5A46E2F0559067592861
