apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    #ENC[AES256_GCM,data:s8BmYMEOeHTx61lfWcqeb1KFhB5T871iGJLoaea71dZCMwIqGhBkTlB3pJyv4XvCsJA1GgW+9+Ykt+RswJeH4TLx4FWMWEM=,iv:5dAYLHSbz/tS6+Kc7BvJIiKkYK8KQI8YxISIeijptjc=,tag:CQZSNplCoarTpmZT1y+sHw==,type:comment]
    values.yaml: ENC[AES256_GCM,data:a/MpVXffg4ZrmQdBMCiHJ8zIC2108hmkqC0Bb0h1DE7d67nKD91rsoP6GXRDu0HBUrmGfTtlXJR7sw3nHE3yr2Es0/qnTorefxw4njdUPb5G1IY348wrKBQjAAvi/iPxerJ1o76SFfty/mK+0XqrzdB3uscLzhSoj/MrY+vILugQSsZCgrUYRAIXY956F3ZuVaz3qKX1X+PLvrPIA3Sv9Ta7itLS6s8Vf3/1WIn3hq503qeDS3/ByKssPq0FTgMgbTlEPYDHp4ripCn5/MLVOMEIlqgLDuI58Or7fQ/UFx29O3SRl+uOT7o+3CJixO0h1mwubE3lYBPrECmFloBa6S3JA/+nXk6PGL3CzTm8oAmvSGOiwPAi16svz7x/q5QlTngLHXhjBAoLkvp/gYa0LKuRJG6FRQQmu8dp8wloCAuLmkJViOgWHDJ4gqbVHehD8TjKVyqqPZB3w+lZcdtmrod3XQ+ByWGSKFDWDzLGH9onnbvcRy8Fdl0O+oJY1xkt75o5mY4pVPIag2BaBJKqM+C4,iv:/ej13gNnT0ubM9pSNHRlO1fOmwJ9wr38VPy7rG8UDj4=,tag:XvM0cmxv93vQyicEtwy6Sw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-28T18:42:37Z"
    mac: ENC[AES256_GCM,data:UPNBHuv1LjpgSbs/Bcq8EcsKsYq385y/w9WUNR358QwScHX9lo4p039PCo2hmUSk5yzE9Wnwepu8jxyUXRvvTWlBmB5Ztj+ni+oyd9RFdYBJDGFtmnF9BBnxUj8MMuSigMPZQl0u7Rsal3rXysFHTqWmj5K0e/SiKI7PV/ncZGU=,iv:XzUrFjnWS7VJeHWXzZ8rLUw74qZ8/8z1Z7rDEreiB1I=,tag:jLOJGegyfqDjCsWYV7HwxQ==,type:str]
    pgp:
        - created_at: "2022-07-28T18:42:36Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwqXVoP6/dkpARAAwSi7GIabl0K8N0jLOgcauBFQQPK0+80O+HmXPJNJ3j3r
            ipVqPcNWmz546dKpLn46a3aALe/HUDG7grOc30BgjcBOuX/aSAeSiq6iAx57aaaG
            zAnsa+FRh2elf8A33oBrUAuumbEjyDgfWwdVbYfy/LpzWeDsopfguDz2OdjlxaRB
            Mc2MW5Fq6X4A+PtopU5eQG8EK8KrCpAHiKshLOuwxXgDrAH1ftCo4Kv/4E1bvaUV
            YWUHTZmteqK3ojoBCVLKyf8+HIpTiguF3XMFzpzh2wd8rpdqdICg6NQVej29nlcW
            k7VodxYBW38U/6QicKZW+2rIdy6RkF14CkZvf3uK5sKLbFdTZpE+ClhY8ej23Pvv
            UDz8LoX2NUKKr9bZtP5uAycDW6cQNkesrAbF1/8H01hVba2lOE1v2bCAUEHOufDe
            ksa19S2rOtzVK/fZRcQyT6T6rH/2hgXhXoDN7aoGLlxvsliN3faJFuwlpQfEzEtQ
            6atV8YxZp4Ej1Xu4VmjETB7XevsCEPVxYQkC7vcK1c+3AEor1tsSx2spvWLbXx65
            f5E4hBb9KPoX4apwJaCB8AFMBVcicPb9537MvWou5+V/4CexrQzq2SpURVbinlL5
            zakdMLEjXr9uW/NahwrHrYYsPgqSQHpRGvQY44qSQX1vWXBEHu0kqbGE4enU7G3S
            XgFk5IC8YJwbUKcD0ImWmJuD/U8aIQvbjLuRv4C13VF6KCRjQPVi0/dyEgy/uwaP
            pPbRAPZ0HtZ0s+VI4Zerca1ohp8nZlweZbf/63acjdhoyKuohPI+q96vOAPyM+s=
            =tFOQ
            -----END PGP MESSAGE-----
          fp: 2219E1B3607B9FD7499D4A8DFF36861ACAE1EF47
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
