apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    #ENC[AES256_GCM,data:SRIsH1iQJNt5kTxoyJ7/EDf8LkkAxO42tN/61uLnj7pO8+6a90AkQ6sO1uIGKBl7NlNLydQNQ+YbcYxP0binjVfi4zlRPeg=,iv:AsY+v4zNPeeOxiZ9//CpwLHJtnU6SwHxMC3nFcmLs+o=,tag:8pJ2BhPOeUwvtbdrWK5SUw==,type:comment]
    values.yaml: ENC[AES256_GCM,data:RA9kaTuLGT67s8L3XhZTbqI6+dG+C3h8/fUoFO43obpojIFLaPx6q7cOpE3c+JewF2S4KjBmCfEuC2thd4cp009Bw4Vn5KsGg9LdW138IuZWe5I9+rq4zkH/M8xhxqMMziO+64nhJMUf+Ud1dcgajYj776pC/LDFhKDsf2X5MJVJJnhR4i6zY2EFKvlrXW0pjv9My1FVvSe9YmDvlAknFZAmdZIioxLRkmqyOdcPAqjTl5sYwvWdb6pH64mLyrIV+5LCX72Dsfs3uOC5nsihxpRr+vjj7DHdyIr/Megsaj72FYm9uje5XTLd0gHSUHL5/dmwRIqbT2cAMa7EcuKM8pqSRuOKdvCfb/28FWwl2AWvyAduNOA/XNpO5rjBUNRRkZRTh6KUNdgYrQeWhKR+uA7O1P4Dvm1nhUKRRPRzpOJgXlK1a27+nspfCEta1NOIRY6hwUPX21DloPhTBWYj97KG73XOYnSTELQD8REemrNJa6DbkAhTacy7sb48ci41eVpuFcdXF2Oa4WDQ7vMMXQjJ,iv:gCWqsOj80h3a/lCyqplp63t1Hm8Wuw3bbPuR2v+VU7w=,tag:0PDhH65BWkGfJLPadpZF0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-30T15:25:05Z"
    mac: ENC[AES256_GCM,data:JvCA3WJuq+andfgLMJ3Y/H9T89EzNafRwn8CHy+HP5O4B6cldDvI2fMpwqiJwhA/kAKhvLM5Hx5zAmHpzBQwozH7oWJMRBx73jQiaC3MLmZd4++KSuxGPos3MVXAO2u+czaC/bdjzzX5dcwjRxYD+auMX9UgYvh1u1E2LbL2+jw=,iv:aQCX7reH/6EMuDnxAxTH5TZDmxcuXZ2npdIMd7jl8b8=,tag:XI7CZBah6jY8fRhlAY7YYQ==,type:str]
    pgp:
        - created_at: "2022-07-30T15:25:04Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3SlJSNwFNioAQ/+O0jqyKHbHqn+zrBxnNQ0SIlZnk58c3YdrxP4uPdR/Bvs
            l7Qhv8yiB2faVSwpVFSLGmUyZFAzyV3GrX0wJEd9butSWlxu6k5eFvBsXZPm/VVa
            rdHu89RQatB7aDDPEB/W5nNNH/Jo3cc/FFcMO5wUJ/t2CgfSaDAxFrQ5UNAv8zli
            WO9/MoDcNp7OIVEsks6lkYw3Xk+MYRA1tIyREe4gfisKL1/ZiRJGkRfO1K7RJ9AO
            DyqC0MjbEHMP856RtWHLaR5NlY0AgJjzPttMZ+N6cHs40kgkTogq5dde1wLTXYUt
            GNn943ejzz57voBmBAuZuPH3rmvCkp+LpkqHYf5izRoqagM5Erznes+bDDyctvky
            J2nqdtfnrLDA1d29En16Mk53bCYcWYJH1uSSl0GHmYuisrue46qUmlU3MgbFF2os
            vBGv03iIOer1u0r3FD+98TaVUK/50fyHgmGs1gLzS0lV2DnBds8dj+kGDrGWrHpK
            hlZe7gWlTEkLapD12oPrtHeJEvW+NZm7ycygph24JcOcqn2mukfnt93gZKC0ICbv
            qPc/ifCQvuJXa/RX/bi2F/zAmlW0fSVcH8LDarcfH7sLASAIwLQXBG91Jwjjp5/t
            NpRbhANhHC6hhqYZEWZze5FLV5uTFjza1j41L4iFhbt9XwwPEdwdsCaD1aKOhrfS
            XAEAOnQTywRkh8Qg71tpG2e+BTxcIeBKUz3BHJ1YOW9GKOW1Of7gjdwhNCRkI67y
            Urd93Z5FWl2ChUPDIchaVao/Wqsx2GfJCkFcO5Va4emJwc/aYYSfLSCuSorR
            =iZWh
            -----END PGP MESSAGE-----
          fp: 75C4B7A6B14E430F6E372016F2B46290C95E80C8
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
