apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    #ENC[AES256_GCM,data:UwqLifPYu1bSdQFx24LxM7+J/mfiTof4dt7xLv4XpxsPmOJnVZneCvdUZ2J89h6kiKJsY79ac7ChLfhUrKfo8G2YzWl2+ik=,iv:e/QWrApYxWui8uv+nDTZBKiceWiayGf18WpIkhBhi4M=,tag:4fcAHZJncxWWP7AreH4Udg==,type:comment]
    values.yaml: ENC[AES256_GCM,data:gtqXPjaNvvkgn+8R9JdUf2xK4FRMlyYxrk4bgdeMDuUVX7Y+/XY3OYq6j5cdV7LEAuPJJzvEnfjjqVseTmmYaUfQ98ucDuPz0npu8m5Q07JzUIx9CddhFAdoM4z+o29RVb8Z1CmxbgLiWGnazfpo6PPPLPsY5fRRYlkKSRRypqwQ+KUw9se0ol06e+KkyLWU2DQcvXx/kpLNYOzMXqKNMtKFiPFBIv7K3qMMVEXaiLHWLOAm4T3Fi9KizCdlv75dgZJDiZFZd4PXj45Ynr77QpONuzJ2JyD6AkwxxETelSreAFO5t1FZEkJpxUaX1/Q2NURrEgIbPRT+oIoDAKt8UHQ8ziXYvLU9mD84oXN5Oa04rriy5mGeXzYIcVRsTzyJurBGe6qvhMXafkkGAHADG0Ho7BmiQrpJy9mVciI8gtMr+q+68c+H+s/KcB0LMMyGoizQf37fn8pxvuCgChNDbOdORxI4m+lcZfgHPIZS1UxgxbrfwXRJx9Sk9q1CkeiTJ3l7AJ+M5ZReQV7LsorgoSGk,iv:cVSzlciuO0KxAxst3xPm/Xy8PH6TDh/1hAeRRAAL2ao=,tag:KKrux78+O0NeUvt5ZiDayA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-18T18:28:08Z"
    mac: ENC[AES256_GCM,data:ly1VjLCEjZRgwUV34sSvldiM6n+dQtCu1dFb0yysySWon65tvmA/fjg28ad2qQ7r1IEUpohIc4KqVRkSlsJ1SU+SXLAmpqqb2A+Ur5RJ+g77iH6H6HZSeDYlAHLy8/39QMwWNFRlFLYRce5f5HB/DqzxYve7k43hPTjQfHwa4BU=,iv:uMTOfxOepbvmITfxu7hLEyY2K1FDeb0uPBysCHmZGLg=,tag:EJVhmLaEZiX8Byxv/HSaMA==,type:str]
    pgp:
        - created_at: "2022-07-18T18:28:07Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4Kl3IpyWPi2AQ/+PnPs/i+/zBhoqnAiQDUP+R1uIqnTVbRfJ80V6jOU+2Lj
            SrcNDG/D0TXUrDhvyy1pi5NR/enulMxDjgf/MRld7iqeXKT21Dd0p+LcwWkWZxUa
            k1CkE/GHPKa8KFI3ID6no9CDZBD6iO0mgZgfj0upbvEyYbQrEYzsOT4rv4+CN/KX
            PU8aM4m9ZG8S1Pm9fTicK5aameCujAtsFEszilXy1MSV8mdGDOGYlWC78/OuBIaq
            oEvL7eIp1TaFw1uKb6nGQa/LyTOsa+6+b/cqklN1MNf4Bqb0u1ger8RE80SGU/MY
            8Z4hHGjhGK7wrWicK15QN9MEOzt7keBUDvmxdFCuY/ufJqBaZc3lwh8H4vor8iuR
            tZkWTBElfHcd589iaknY0m4AFj2mv+RbHFP0BG7UoDZA8N9WQ2Da5ypkna4iTKiX
            MmHYYkIV9a7WQDCRvWxxH5rF64RE22mSQrfw2aQXjuE6Tc36zbs2t4WK84iqfznH
            J9HrVZWkeIKEdINTg2uah3tV9N+TnuzlAX2kjXTuotGbDXGQsnBARJQ+T3tJyape
            /RGeO+97rM5ChxWf+NJU4HWsviF/cxZvng9QaG5zCA/aI+Snv4JuPnJrheZ3sDr7
            f6nej1uNRDTXcwOPAaD84AUx1vnYkKlZzNLma+3XxU4XAmTRhHK9j3x0KpsYWmHS
            XAHMT5of7hGAXRtaahs1ziXKTVlHJW+QWbx5JxMx8G6ws80dQ2aEtHFBKj8uHCl8
            FFCBFrUUFpAEJamLpVHLP4aVpbEHR3Hpi5M4DFggb6xsHwLJwVrlMJwNY7Hd
            =1DNu
            -----END PGP MESSAGE-----
          fp: 48B54B51C431AF6A9C199884E7AADF2FDB4597BD
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
