apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    #ENC[AES256_GCM,data:zhEtcLayD7jKhGrazCTOtdrr+oh47/FwccEqFTi/O9Dub3Ah19tCjDmhxLNQ4/lvNNslyGcbgDJ5XxbiDlWfD0/7DtC35/g=,iv:FgFAIuC9LG4H6TDVbXXbawKBJiNimDBwqQMiE5N1aKA=,tag:dbg3d3cumEHahfQc7bEEtg==,type:comment]
    values.yaml: ENC[AES256_GCM,data:WExdlPNOi33hT0GFSS55KNDU9knwCOjiTnjJMjzQiHqogWi7PhlVAYVONFpkPkWPXxm6Tru6OGpLFt0Z9O77+6Aprc5tt7r/BYlrE6AcfalHa6fLCIgcijQ5URKR7Z6bNQLJSpmSt6+whOy60naCjT3NdfDqET4VWuYpODpii8fvJT1klFrstcVEWb6aGj2noSuk0Jao36Ag4K6V1VDT+JwMopuwuS/fDCZmuMQ28wF0QgrJANeX12OUgztHCu5OQSYWGNNN1sYmYQhmYq+2wX3flFYCTmDtAYE41jnBtkxjr/bsg8pfv7gb0S1K0lp7mD1KbV3DzY7kM0TXQKFAAnulk7WO9JyiXCAni0ITldcflfsGwPL3xGSgvW/yayP9jfp6CUjnG81qmxBEyZTRIHHveQidYclWqF/HMxwcv9qjRoGHKAzHOpR7Je0rpiUDZEA1JGLrdBLuJvr/QM1ibtIpOpAcktLsLECamWoKe/1OI+4wox9UcUmCXqTH+QvGH1PD1eWvbjjGyPzi4j8bEwHa,iv:ITTCDa3A892RyjaThkjNMGt4K1yiBTjaglVyjB7Go1o=,tag:K/ULgpkP1PA8T6oifX8mMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-01T19:07:46Z"
    mac: ENC[AES256_GCM,data:w1MybaS7vE8rbnQWE0z2xan+VjaYpP9CfmN0W3NJYY+/GGeo900maFgLQLdY+2hSiLzCJTOdeC2olUEoR7nZM5ximgCS8m4iknIuqUXCDUfGqe5pJn94Geynrg7upymGVUxOgBfjnEik/l91Jjxne9wByPddlGrCywPS6SDsPvA=,iv:/NYpro8hDRNtr4QBaggoCRUSDgwBpBZSFgBjurzOOp4=,tag:9K0r9/5K2OjGJgbtrbW7Fw==,type:str]
    pgp:
        - created_at: "2022-08-01T19:07:46Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/pAz0p9mvqsAQ//ZbQuT0jESxAltTvS5DoKseZUiNft8fgjfZ9Nh+emGUMd
            k+qgIc6mEUuWmuxG/S1IfVcQ/+k/AdO4eoq23ak1SxnHM9NVSj68ms/mn4aJfLwD
            IIQF/+lOWk4qYJCzPWUq3EGqih8jrFZ5/yAzzgo0gynKP9MR+autcui8TYF8T+au
            5V1ZZ12ojSj2G13iMEPk2Weg6Y0VhUwGLVdxEmEe6dNLyUtTlH9dX5XTvqOHVMfy
            DiDaqgXnBkUiNab+QNA9F/ht4THcVGklEEu2EJHrLlpGAKCSr5obVHc8yaGgnuR3
            W9vsr4ML5jgKonktPlC/iY0HwjOG99oSGGGEC5FSfQ+keX11HynfsrV8BEqV6zie
            xNDW4geyS1WAOEa5sBt/qWHdQkNJFpaRBH7bvp+h8vuHKUfK0IZ54rr0pmZ7ZG2k
            XsQWlhKoQBqQT3GR3xsidduf75Hfa25HOowyUs/WkpAPsBI4Q5344Bxu+IL8OtpV
            l4oqgbhK/rVX859YGz0oaztzPspu5VSLf/AMxw9T1GGR9luw7oxkPbZE4puzEiQ7
            LuqTVXbl6A9PSIjvSw4wdeno6ySiyfRnuUhgfNoOPicmmZmMEMOFTOlcxakmH9h7
            uxSrXIo8/NbLSVdHg3KU1i2ooOiDtjiPYPEa2U16CMg4bhQLyNcBsiI6Vb2RtxXS
            XgEJZNifK6HBErNVSpYzwbUJvZl6fXCPE02ND/Weh/h3ZTP/TfrbQIV2CioG8rHA
            tLnaSv0OCEXsq+H5PI5z1WW4Vo+9gEepR3dsqTwY+CaOkeuSHjHTLiCJkHVyJ2g=
            =0GK7
            -----END PGP MESSAGE-----
          fp: 3333B15D629FC9F671D1875C433ACA89EF65B447
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
