apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    #ENC[AES256_GCM,data:7RO7e16yjCKACNrrYIEkhvz92Sv0G7wdbXSB0UeaQLsN32bm6LD35gvy2PgeVgveqPQOSrum+5MVYQqC8DYUhOradams2Ik=,iv:DTZX39jWGRVysgf0+usIp2ezmVd5EgzNLWG93wrf8JE=,tag:fyb8zlhe93NzsDEbTCYbrQ==,type:comment]
    values.yaml: ENC[AES256_GCM,data:d96SDm09DyI9wNDCLD5/yBqFHgbluHMPc7mwCbINtBsyCjZHo57NeWxbaItBvSUZyTheW51eN4OsXPIMQs2Yu7uLwVB5uOachww7tIG2ANh2IlOqN6lChXU4oJnxu6bwYjRiHJd00z/xd2cM8iEbgMgEdauZu3JdP7Nno8I4/lQZctlBIaISao+taznLyaK/HLzHHwoTXoZHaxTybhWaL1ZhDCBKrsEUDmSii/cTTMa0XD/QDBWAV2yt/FSnjDZOj+SwJB5m84f0hDqDPdy/zci7Ah9FFG6ZNyLT3+jxFv4cAJB0mhkfkMGurLVPTDZ9tCiOG7xfR4ZxLWvoWHy8HzXP0YA//DYrQt/BAUfJnaI7FjSwBp47je+SU8FP1piGcReDDpgVVv1Q7MjvILBJAXo6dlcTBHD80zUqJtBF4IILZ20/EOwTKg9v+KW2NPJv2GkRVkM5A3WS3i1zDJFSoKqeoGBBxzckqYcFdd/3MzI4FERtgt6yy0eYiQ==,iv:KuhTg/7jEPjFw/t1x5ZeKfKMpAaoOAaonTThq2GAPtM=,tag:E3TR6/twSlRBiv0DamQkMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-02T02:17:04Z"
    mac: ENC[AES256_GCM,data:00jAcnTh0tZEnegnnUUhuvbp44vLf59MvosSUhLvtp2X7yx+rMKv4MrJ6Z8O3ZEH5wCbj40EuuK6u9K+0WxoaGcuQScAXCe1NR8H9/5VEkKpBMADk9+aV9XXlWvXR/RNTie1FeAagKcnXC8SwEtDXilr7vM1mRMQccVJjCmczdw=,iv:JKf+yg+6LwfnJ/0siAM+oWAemxQR9pyp4csdHH1zHMs=,tag:yg1EQueKuFeSd3iJMt066A==,type:str]
    pgp:
        - created_at: "2022-08-02T02:17:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4xQHgtFIvePARAAi6HwggsI9c8e0zP7a2JitbU/B6jkPQIbTg4XA9N3OMZz
            b7WI94IRSQbr8Z8BFFSCmUiWBGVMeDjouxHWqumh/OMErvqE/nErovRhVxxIhq3X
            0F2wp8YL6NWhrJGdbjTq3F1vq5rD67S44Gnxg8K5NHtobRWiCmSAClOk/zF84zx+
            2sd6FMaeb8MKZDj4rSW0rORqlwKxI6HgGqFQQ4ickQLHCfbVFOhhjKKjspCn/kfL
            ZdyMfYMjyomb9D7PzoMUqrNiVx2uKVj4WZMX+p/Kaq0M+gi1DYi5yNdXTzDjYCM5
            8ASf9oRnVZRhAcG0OhLipR+HJpvYL5QPrB+OvwEK7LxzskeMI5QsdOdmWkKn8ty8
            Hpg0HDA+4OMMNGJL37d7lQE/M1psxITp5oeLiXmacKeVyNGlKrRX1dhi9IiHwR2n
            x+kVoVji1FrVFa9uEqiJU4cVvvenYwkLaxTEDxpCOLzZJzFjM1eyafVhrcxPaX6l
            u7Jj6YT1+V67MNfqxJJOemssUIJGr/pkaaCuIMnjNpEstHvMevnYWKca4OrI7gN2
            FIWPHnJ6ZlaJzALRI/fkCPlZ4LE7RlQdx9hbpZfVa5TqLX9boSXow3hagNXfSZjA
            guQM7or2cmHJ/0u7L4FdpcEVT4lZapSvBQ74o/PEDUSvXGH0Hew9JRQXcyH/lh/S
            XAGbf6DGbKw8pWkZDrguy3p21D+ptj/tqPyRa7AR0sYUTLaOXcnT5LW/tGNlw/ZG
            vKo8mh1MZDQOs7hxMcExjH38IQvt5iL9MbhxM8M1+zo1jFokrnEOp444q/UH
            =+PBj
            -----END PGP MESSAGE-----
          fp: B4B0C82E0AA6158FD42423C8F68DA65F74428F88
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
