apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    #ENC[AES256_GCM,data:luaPxrESOFXAW/VzF6fPL0oi8Lm1ZSzjpaO12aD+vFuZ8JxbhOARNUkkYt5p8PCzZFUxiLg+gpwq5lIWbjNurYaasyYS6MM=,iv:mKs81IOQQlIJA/niPq6bIPkE56/bV0BHB50p729t5Po=,tag:CMALfKxnCiBRZGsog2jpSg==,type:comment]
    values.yaml: ENC[AES256_GCM,data:1od/4ENXg6yISdCGD+b6GLZumxZnEw+31o/FpLOUF6uHLnJNyfaa+beWcJHNTcsiVwR/9AeJgqOrpvfpaa6AXdLzsYa0M+AfQMTyGmFPqnJHbvl6X20CSuvLtkthidmDdI407CCS3BnKKpg+/v2ydiFj6MSs7W4USCcEruDQ9jL8wMUQX7uTFjemm6jbKMUvAqZ/ahW3gLGjBhnDgFhpDfLB2D2ZVmf+YekOtiydFv4LikmrrFoAD/1M+4EUQMo4C+QvOsjAlkLTo+JTQe3O/JYOTCZFLAVwT4Mtpag6CKcN/EZnj7SGEh9ALJ5Z2om0U8wLM3uc0B0/PXOql0IEw/5bQ9hutfuuIMnT+q2DYqFvJ1tUffMaODGEIZ6zb4LeywUo05cnKqiOQVXn3kdvzr9NdwU5yr1uLHOGuqfwCSGZToE2krRaxlCmqCEvUusG7hcFZVYxg5qq19tSBnWsQ8P/m6j8/vf3HUooemxDlXC1ORFdNJlmKX08rQ==,iv:9IcR7zFiaLlnH6qsH6zyuaQPUP9xnAnvmpyh8BNBFG8=,tag:jp9O7mz/joE9stkqBmH3RA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-02T01:10:21Z"
    mac: ENC[AES256_GCM,data:Hl+oIrWZfD7f/CwzJlxG2n8qUcOKSfA+UOv48GZBw3KVTpqgpkS/Y76deTu6PUwsRfAA09IYxJyvlaKmR1h64RTf4yRu+jxpMe10nKmD20+wECHRbKTsaHKkQ8XU28/swGuezoRrZcVccd3Wm3DHhjoIDcXvUcyMg7tkbKJ9qxQ=,iv:zgi5s1EVNmHMkxO4RhYwzSh48KVmSo39835kz04JFGQ=,tag:kYZQPlCJeGQLTZo1w5Ta9w==,type:str]
    pgp:
        - created_at: "2022-08-02T01:10:21Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2rgBStbi+HsAQ/+Nv1P6UXQNSdV1EHUoeprvKWjCSuhsPmsUtdPOAukglAW
            UPmAQz1CpqlkvDrLgc9NZ48rGWFyMAl0kUSNh+p7533wCdQ+6dla21hqdROxXvfG
            GGn6zvbp9SbLfvnZRNRDBI3FKpN/bnlZyzoytvibMIP2jRzG0EM+aE8YBeaFg/t0
            pReOkbCEhzevEnnT/Ux3jUfXMz26ex1n4ga/sufPBuNVo4oHjFI63Rih2NoG1v4Z
            Rg6+EjesFooMVNb090mtqs4DVZCxN/YzEkAaOETXavR24beMUjzYDuWMkkkC893Y
            egb5+61AAH9blG2gycIX8hgJIxGVOaP/dmbuPxOE0VJqKkl9W3CEhBoj/WVYcKXk
            Dq0S4RxNXAArcX7DDkt8OPq6+tybuLXcXAVdpiXdqsHwAMH/O8mWByOLmD1JvuTm
            8Ys17GFojpVAXAbR0khFAUWLYM1qXUc7EORBoDTK6gXbEE9yDHxF/vHBpnoJs4He
            kQYtM+IQgBtqrVBk81EWHLOTvchT3uMiTFHaRp7bYWnvrFnLEeGGHrhhtFuEnQLZ
            0VRcFaIi8IBt4zzXNpERC2rLaxfog4DFZ6SuJ5mbG38b7lgWo6FkdJKdqIgUIlyg
            6YyS7VPQADXwTv/FDOumQojrMTjaxbZ2Tg8GwXPbDxK6CJ6K88ZSLr0XZD4FS6vS
            XAE/HzZUKmDsht+18bdX1EIT4hzVrAkTvWROlzqVmShNl71bMMyKABzL+/1RFyFj
            380ncaLOOUv7BnAW2cb82ZojQhP6uiC4y2eqlFh8GAfOCC2n4te2GNl6gVsM
            =PFFA
            -----END PGP MESSAGE-----
          fp: F4347781B6B21712B41EB762FC6E2D92F38FE74E
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
