apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    #ENC[AES256_GCM,data:sNKfuyIO6I/pY/KM6z9BgD/7dtd3ygIqThHuRC9C3FVjsl8LFF+z3lxvRFo33BE/KAfcOa7rWWRPcAjuuFCGn4sqPWvapeA=,iv:Zh66jZcxpFAiniKCfor/x8iN8zXBdYbdDS2ZMXFpZac=,tag:uVDgph8TguLd/olueMQZ0A==,type:comment]
    values.yaml: ENC[AES256_GCM,data:0aqVmX0aXm7trBz/qgxWBUNX3zoThQ2VcrTfj7ZDRl4MXhJddWegt5h+YyhhNRaOMvIUNHoNGwS3tL4VVGT6lx5DFDpFQ6M+LwEiIo4IZ1krUl87gUUC2KZDbh30qX37GPVIOOVI64T4RrLBJqFu+OR/y1O+KqbcPauxXpGDaK6dNlbtHvrLPCooxNVaNfHOWb+K6DmIMmE2TXheeyevsH+GsA0i0kVtuAMlD3ADBvp1bgNbLVb0JBK92j+OMcviNqznegpYuXP4p6Bwpimx9IBlRqfr/tRQKNjd0tuPptmvmbRAplZjtFdAGECgbir/Gogb9kUQ5cKGMUPr+1w/q2aEz5eCTPMj9A2cJ75DJtf4pm3fbZtHSnV8pz4W5RWWaDURhImL9NwWjHXBJpIgElzcskLj1n/Cx5qRosuL7DmBkd4BjmnxoSWM8qaSkEXWXUYd63bmJLkicPXX/UNzxUmvWgyPyKXMBBgIrcV1TCxqvHPQyZUFLH6zIA==,iv:9Kr9wZUM4Te1V+Qf5r/byUIa0ZkSTKyz6qyOlj2Eq+c=,tag:1/QHx0LznqYkc+U7IjmySg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-10-31T18:09:40Z"
    mac: ENC[AES256_GCM,data:B0Zdw7/pL07FK5cedHRaZ+MDjPafdjuPnb8xVjoGlvmb/x/YbJenw9V4fh84e0SJIhcDQ2/xeTsjAlya3CYM0Wvoq1tfDt6cR5mwhd7Xq9ChgnXtzpzDs/xuzGBd17Eb35J3Ne71478K+5qpwFNdsTngJEA+rCtTItVxU1Oai8s=,iv:ytC+wfd6HSVsREqxbLBx//ZZbLxZdgHSlXHlCjmbSZw=,tag:ierQDC0FHUUX4YLcPv/AUQ==,type:str]
    pgp:
        - created_at: "2022-10-31T18:09:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4MOZ2FhWNFCAQ//QxmpnEUHBEHjvUqnuLGmFtF2cFKttJd9EpQWB9vDzLk3
            rCEhReOJ1F17/8s65RWNjVH6QyVpsy2ygWVRYVfuUqpeDXPujUpXBdufZcS0emEL
            1fez9UdXInBwy3HAxazADjyNrJBkld7bVSaMKYPcdF4YEhzmRS0Rj1xOf0FCd7tW
            B+iCwECm7LwTGGYl5gzl+Ri4Vf24lWhfnUQhxcZSj0ch+bcQI6hnD6PCJgErXObj
            ih5UtJeTjcdUf8eUBiGmJ/kanXPWSOYZIfBOueeXRmpjvpL8XQVTmuCYCstFNDK0
            Whpn/b9KCcjEHPDeMFlo798r+fFCFWUcwzdvMaNu8cBux0fGc4Xx+HiFSf5jw3vv
            9IR8Cfji6co0/MyrQoQ4vpiOITY3oz/rEvzFwZqlCGp29CHTyUaAwmzDDMW+5gAb
            Yix94KzrIvdxnZQ2UxLVZXz5sHKNv2EMJkD+hQDZo1XjR9LvkwFhBUP9pylAcPlH
            HBBPzmchbE+H03Mq16pKSfnn6tHd417YFdXUbOEg3Bg23DGwnACYZ/3bdXzXizAv
            59HWIV6WFbgllssatm1r5ZJQoz5Oc6tk7ZgKmDxT3HKtDOFDBtJ0d0lHiE0323aC
            Z6xPSHKgYg+zijNW8i/+71U4KxVLJRLoITzuJkTYo5TS1Z+JTsWJm3rGisYgM8TS
            XgEki4XAWvCdlP7b17KPGgmtlrirq7Wcz6yOd4BnaDBuaTLnpbqG/FGjiLKKlaTZ
            PmVv48OB1em2sSc6BrSDv5jUva+nIuTYnMeAhOdMCOsFydJTo+q6VIL/cZsr2M8=
            =HBgX
            -----END PGP MESSAGE-----
          fp: 2ED6891727B0A21F0FB0B21C0FB7CE892BCF93E6
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
