apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    #ENC[AES256_GCM,data:TCGmZc4Wvh6G8Hp7Pi7PlLLxoPobm91C5Rqg1SOif/foy1YONg2/3ickwpQWSoTPfzHBoOwehgEZsKXW5uB2nTH0Fyai+Ac=,iv:Xf44YcXUgg5OAfHZ4rnzQz2u77QPeo0fqAOAqtFki2Q=,tag:crpm3/iQiL6nAPLySTdyqQ==,type:comment]
    values.yaml: ENC[AES256_GCM,data:GqDH981AL33E6uUqjU8nG6zXM9oQXSggdpyeQIW3h4LC2ItS6XxyV8qrKtqfH8AJWzfeQ7H22/D7qbR2bB1I667Z6V8neK83kO9Vztob7DbHCfGqKW0qr6fla+iPfxYW51HlP1Km97lBbnIcFQZnldI7j8Q/NE7yRjsvXYn2+mVPwC26c6mSFUIsw+vZSiZQEtLQ8hXnhEgDhVvlYtNIok3EQb5W+pyuIHQLHmvQINxsjDMRJXi4Yo0/gQqWQDW5QaCVXrCRXk5v1RWIDraNt4QVtRL6ogD4d2Vqi9VoLWtN2UO0IdAmd36erhh/wqV9oXVtMlp+LL6FgBdZRghpjAp9h7gFrz7Gw15vRfRAStaU3mupIjqLSdOSx3UYPAoQbVamfGrx2z6M991Lsd0ePGT3QCJdWgqZ5WRysEhhDkCgiFRjcsbdMgbjA0g+BHjCqGV9qnqebe7XLRqb9nx6M9SnyteC6cmMUO1BLRZg54chDXAJjpV2dKQwmA==,iv:VO8go43dDI+rSMRU/v+XGk6F+DPkdOI6bAlrecxEx5Y=,tag:jLpkyx8uGiP7dOtwqG9neQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-14T17:51:43Z"
    mac: ENC[AES256_GCM,data:6pHOA1DojXIC1hhgK21UNCfQVUFpsYgJLBQcMUMe+nCCrAHZrWmodgWSRAWkTWXlcn464SuQNhBCGY15S2QOaptyDrvKrcQp4kejIfWzcqcBaD7IO1JUcNgOv5T4WZ8GoxABQ/WlTGfoxuCYHpFZAqv7kc47xEWPPdhuqNxJzOY=,iv:E2zTwpy4vjn4kkq+AsBPng/dCxw3VuuH+Bb088fbUqY=,tag:kWqtjwCV8ft2avlqOUygkA==,type:str]
    pgp:
        - created_at: "2022-11-14T17:51:41Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+pb3LEgUHZ1AQ/9GGVb0t81pdqAds2Z6XIx+380WbqX/EaWYEsB+6h/wHOY
            G6Vmna5/U3RISkKdkDV9wtUA4ZKKpriZxCdbbVCJFIn8WGr7wWSHeJiaQrxoyvQy
            pwqh4PVCWtY1dAgVzg9jO+F9Tg7cSipddi/dXAcSujkqMUVlQCPpOE1Df2HuVSAP
            IazQ3AIsg1//NSjM8Vpna2d12Z21HxU37DA26+G6VtJzBTbcb+vDR3S5UxuLWS1S
            b4lzG1jdEiukAw7ie+1iVEfv2G2GpKysnxHQVz8QCxrmIDBFy00+7rRlrdPsIzhN
            CDN0n9asK2vLRw6kUBZsT5QQrSH2jZmxWIlQBNK4L1W63KU4kFmkXePR3U5Du4WK
            pRrE8GwwVNzp9Q7Sibv/QlK2mibmPhS89JN/25N5ZScIBtMm+vUJxpAzYdEk8UYn
            POAvlOkWYdnpHzNpZ4AiJ6UYheSdP0GyYyJOgC2ujSnZKc68/YahN4ZE0uhmTG5y
            L4n3YCHQgoHDZo6t86LC2LAbxup77h1tpm+b0825Z8YxYPAKbN9PEvEDFsW9HblW
            xQXANMfDITsmWxf2sHbfS6yUs6O5x0w3/15i2r286M/4wHRAwvVk/jOsWMqkHXfm
            EbXFAle9xEYRG3sSzCAyGWSL16s/9ey6767lc7wW6M4jdh6yB05k9XUhYXhFKLDS
            XAHHH3+ZszoZR17EEff1hLIDuW1NCzqUltxiR/39PhYBN+yVzLpSKFRa/REvJoEW
            U6y330stxnGrjYfUJJ56waMVqL/7XX6x5onR1wWhIeunSuu7EBzR5+kvGFW1
            =cmex
            -----END PGP MESSAGE-----
          fp: FC8DA015C23384C3A09930A15F16F57012003E47
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
