apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    #ENC[AES256_GCM,data:kI3FKC7m9vTAanhhNPXTHBm+mTguVfoUtgjTr4btq7HDsh5AMTLX/pKH7Tt7ikSxK9Bgeru+YIRYeiKv1IkYMRK9BEYaYL8=,iv:AMA3VSiifKyAPHQ92DQp4rFgQyXU8h/zvh6ohng4x4k=,tag:yLUIOYOPGqChMsZPMAm0bA==,type:comment]
    values.yaml: ENC[AES256_GCM,data:8KLd8w+9x10NZVRQWocOqjvg7dS1xmp751jfvXg9CG9rPVbrGo/rCY9gRfNCAVvUMNvN/OK2ErLZ2uDiRkyOaQbqFJNUBOyPCfBAqktYqHgVDD82MGRQu0iC7uXSN1tV15f7gZo0Z6S1g7T/BRFjkRTvIX7X437uTmOoGcbvCKOwesY8pcpUfcJxSlh094F3XfwrRs6qcd8mcWB2CBRaEggyRHToKiGqvBfnId7NgvffpJN8LDgtE6asnTvaJesm69vw+QPcmoj3L4xArdNXpDrWpUKYjL2POSK7GHIu4nbFUP4qEkYtC0yP8+FBvXYKt6M2QuU8eEXwiNNvM5l7ZoFuMJyMYvIL1tjx3TjhnVgxuW/6uEIa/ANT2Xj4RXJJtZGrtdw0/+7o5LYRNhFLcj4R17X7EIMLnO7msw5dWl2/PF6drwLJ38oJdp31G0jbElC+TLi1XQz+Ww65Yu2MGLWhICkhlCH/erEgQLUA22SyGbzv3QmziTMeZg==,iv:UE142dAvGoL2ROU1aR8ah6dqpAzflTrE61KThoePFUg=,tag:47f3BJk3WLye0VWghX+xFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-14T20:42:49Z"
    mac: ENC[AES256_GCM,data:Thfa5L/IJ/hGq7EAmUbqT36E1jYbNOMw8Lsml+wgVBBKiSCzM1jm82YA5HwBujWKDQ0Sylp/PKxGEcE+O1+ELi7PFgafoQcUgWyQ6tGVaFik2ZTB/ZyLgRko8YT20oM59+HTZyE0Dk5ro9ncEiixz4cF1RGJBVYDXrPU7IB3jBY=,iv:M8tlHCL5bz6ZHZu1rPrEL5E3n/MSLdL90KBMYbJGbgc=,tag:W2F8zhQOqcBqBZzeMWfh5Q==,type:str]
    pgp:
        - created_at: "2022-11-14T20:42:49Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAw65y3qeqCoJAQ//YlVukzpraHArgFW9ScTaZqny+3IJvPpc67UbhGgv4D+n
            1hC7wqhJcENYPmMmXO7V2XtiGgjubIamquqNmbv67eyZ7JzggZ8PhHLMlBzSFBw9
            mdrQcnGcNpJ7VNZnKYGF4F+B2cbl07jwF3DeBpY2JejUFMsXn927EoWBwqfzpE28
            YI4XllEjB/BbWJmh/yDaCxtksehx09+FYKxUlPaJi9L8t/CulSnP0T97QGHETWMZ
            7bcFcZdW5p36vCv+HXahwEchQDSRnqnyRUe6erGJgJtgV7qIOqncvL+RUyoKs2xd
            8Oc0NCXQGcDQm3ClRkVAzWcWAm958QRyWXiex3I3qK8ffJiusjlQuLyUk0xRN8tL
            iWuRz13AdhaE+rYxchP7v6JWHLdD16tcQ7ZC2ZOHIFRhfGaH/ydjyUcJVO3Cr98S
            xcOj3bb2BcJLyS1VCwdzqVYk7zZV/z/6uttwEhX1ScHrl+IyLXhLQGanMBfLhWR+
            jOjCE1ilFoqQAyua42NkkgAroYaZIVGo/F11hQYt7Zb41Pk20+hYsk3HSmwqt5yg
            lrjEnhd32rbfpkgSGBaqA6f6JMWvWU9VBwTKLipX/FYc1r2tlsM8Jo0QgjUH7qzs
            VziKTad2VS4XWKLJw8FDozJKAv+D65F2yBksJZK0mKttSPw3EOkh90L4B2m2yDjS
            XgFQh6O2N/sxPhbi1tRn+4PwJFU27KdRKZLVKJNmINmL+N2VCeVEz7AV9oXkQ59V
            98gMNNyTtVVy/em/H7USVfr6lGh8ixCCVM7J33B/uqykK0PQv6BtSE/TRpP1jU0=
            =TGG+
            -----END PGP MESSAGE-----
          fp: DAD328F904BDA6F70764F01E0A54A5BFCB839F81
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
