apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    #ENC[AES256_GCM,data:xk8pDL7KzWqhCDsx1Ed+5wlWS0EgiLITBFTHSyHjb9rEACiS8X2v5twaF6678EpjORJ9trOMKopUZHXpNrS9rsFlv7YFEe4=,iv:DgXzaf+2SrxdiGdSXockkOBAvBkvAWizwCSLdrR5ULQ=,tag:8VddPzLb1wHRCv+N3i0B0A==,type:comment]
    values.yaml: ENC[AES256_GCM,data:1YUykIXXCI0dDbNUHoML+c5kjgEYlfQjQpyBQ7DcQ3F8zEkf1O1RXLZaxaUwc2k1p+1YeMhRsoM6Hh4kdPU3zqeN3Ba52II0psAO33hHwE11gOKSIlTtOLQWqrcKj16hJd9GPLzzZOu6ayzPZux4AtYisMiABoONNH7eQUQ5vm+up3qtUjtgHmL+5wbF7yTP6CPAeEJoWBKqkLjHXbSzPiIG35DsK/yTiaTWAZ+vJbl1ovwjdd3qag8W9e9F+Iekq7YWI9lX4yBdIfq+dNle+FHg3IEOUDc0nwqIjhVP7hXjbbdp13Aq34QDsgQxtvZl0cRBxBYfwSQuODe24yAX7LaB50AIjwJ33PBXkSWkaksUeJWZhifdAMf5qM8YUGNcGdt24YAf4tdPw72oUzHE9o5hgH6sa0FYbQuIex1Y3YJNeZMCRxuW3yLnv+JKwdct8Am3TmW1IUYSvHuOmrPDTSxaylSZcKahxQVpDyVPsGf6UPVgky75MltpCFmNBafwvpc02DaQbYIwTl9VMinNIsCQ,iv:txatTbQ1iueOhOV9yjlqsKljY2h6LrEJ20dhwTfjtc8=,tag:UkSAPZvGe3+cz914FDnEOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-02T01:08:25Z"
    mac: ENC[AES256_GCM,data:U5YvC+KfnKrSwzFAFwu9yyPWLhtfWDbVX9gjWFCPlJFuwmC0ano/WeSK72rcKUl3vTo31J9+2nE5q4x8rPjsDh+TVoLpcMdAJG0lh0UujAbe0TM0dIOVXOdTa+jMy6LfXZ6uig+tGmf8DWcQoJXstAy2sOSL5eGHMA706poi6F4=,iv:x+n13kWEBrftK6VQ2VGCU+ttJJ8TQOV0Dj3za0F1ZY4=,tag:TA7MF6nGyaG8jvx8AqyoRw==,type:str]
    pgp:
        - created_at: "2022-08-02T01:08:25Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzS4CoZMfg2SAQ//e0EleEE+PRNJGYZx4wmtf3n0XMZf+Y+eIOxNo/h15/6E
            l2erQP+6OFHwrrVl/OP/lJHiwnaqIWVLEQS6A7UYGsJ+qyYC+NYbz/gaAUyC79vy
            d1kEcN3SGwJ3Xtes93nwO9owZzwrlkY9ReOevMhVWLMjj2+MdBOGPcYNf/7uc2oT
            PpI+tgZorpAkOTCV44nSMX3KQcQkc5myTxhxV8B+td06KPTLrws27gGS5T02yNNF
            IztNAXSNVOAl2Ml1pxjOMB1fEWHMYRkSsOaHQAHncXYlya3HF5/kblnbY+fUhH+D
            LSI9h/9tyLQK1CsR7WyXu20c2ZNFw+10Bz3czhdJSOk7XJRQpP/aIYAUask6bw+R
            0XFHXWkNDHuqvFJx6VCA0KgSaP3Q0fi/mgLdK4EmRAFvrFoEsDG8aODOFx+qG5eB
            PbiQHCjg2G7nuln1Y+ZD9AFdyP+R9ksT0frwqmjKPcIS7SkBoJ1YXi+ogL37YOsH
            FZPDZeEq+aMZCDl3Ga90qEcmd94HAssVptRBevIr7E6cQJr/wT3bM8CrGO6EUwO+
            ftym/VW1cEmqz4+tZQshruLAo3htZAdtth8sU2u8COfpTALf59d51h0PAB9DRRq/
            TN1oPDtqKmRz09juyqM91lvm6l4p5z98SwHZ3E+hwbf2Cr9/d7kg2RijYQC3Yn3S
            XAH6bmF6QBKq+8EyzO/BMSKDC9SmNZ4kH+V7npMqTZnUXA2RAyyR3e5KJJC6jU6c
            9GueoQ9CLTM2+D3RqeqaOkdoWsEyzIxU+naYS/e3bEe4v5SxDDlifCnWpo80
            =OLJf
            -----END PGP MESSAGE-----
          fp: 003B606121B2D38820D90C1F4D8DBB474787AAFD
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
