apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    #ENC[AES256_GCM,data:lrFdq9DFyBlwY47j1Ag9+Mj14i0bIh4l/rlaq5mwofnRlyNHtpwTQNBolHFEHPsUvvW5guC1xMPIoa/xZY6MKVyslCuYjh0=,iv:ORMZgYeN8802OMD+0eNIO8e8A4ZWwEeVjFcdzX+vRKY=,tag:70zElZCWdJqi/lQSeHrPSA==,type:comment]
    values.yaml: ENC[AES256_GCM,data:VJxSwX9wLR0MqVFCBWFkDAm/q42z8a+QMGKSxX+zufh8bJw25wUpZlAzs9KtWRvBEILIPwIR0Cjx2/en85k8fI1f+mVN5lJolc3cSN0d1SJkf8J0XHmJpphHO83LSTsE4fqtb0rUabFFJqpZfvwHByWP0Wij826rZbkcaBCYfMezXDAYb8HSZrgGJA2OukfT8Xay0fkV9TS4sWvp4HazeQoytvrLzQJNJRcfVs3eeXJr6K2JgxcLAldPsBi0aeG/DsLdgbX9icPbtUPrcuO9uX2ue3enFBKSaF/7zKioiLsPdNBsG5kpLwnAOXpSilNlZo4Ai9f6oMcpy627QeCNPP6/MmNifC4wT1Cr/c1K1NMHouHbZ52s3MmqJzaKBM/OlR3BH50acW7kTpGr3PEFoMe9/sDUubhjWJJ4B/JPvpYvbO1MKCUqce2QQ9WVbDdV/848gYTWoDEJifRGtanXdCI7XtGpD8ikfcpSe7q/1nztbYblK4hbtUy8Td/XG7xzeBjBmC6WIaz3cSIYShNkXnBD,iv:hVWxKJ1cqRIAT9kofy8OMN7g3h1evgewIct6lJtWIZw=,tag:vhcuVMJJAWRLRSMOTMIUIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-02T02:18:19Z"
    mac: ENC[AES256_GCM,data:8c2uagqdtP74jc+rd4c+pk9DVH1e9UgrR784PFvu1f3MmsENms6eCRpgldwbPxjTla6MSxdfW9ka9jlflQoGMV4eEVOCtzKfQ6GV+Pisxvi9k/M1Oy6PuYGzZ+sMhChicqsz3Ss2ibUJ3RIVgpsMP35ANGhm90O5RXeJLjZQw40=,iv:YZyeI2zRN/cAbgDtH5kizrkX5FlnGYxMk3vUmUhQs3g=,tag:v42qp3qK7zsst6JjvN9xCg==,type:str]
    pgp:
        - created_at: "2022-08-02T02:18:18Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5fcgEjs3zBqAQ//e4hrZDLQ/2pB7uOyh8KIvIFoFoCAXFLBkUNIRpVMr8vC
            a07+SDBAMy7yOGbksdDKP9nE+DuLbhCJ4cKp+k+EuSl30fMYUmWY/eQpRibwbLS+
            CCaqeVP50TNdxW1s9W9d04LFfbd738o/lxgoWJ1D+D2MX63P2V+TE7wacdWwfg8C
            Q6aCmpwCYdJ/EIHEK/VMmak8M+o0xbkrt56e5aoB2rIGf/e6oeQ4H9i6YJ27TbQ7
            jNNr9AYeJ7QWHifnWJpo/GqdiyT7cu3Bv6x6cYUH42b5MTPq9JS+f9sbKYUaLQLp
            ZOjmHzcrfKwja4HDDrQpzMNTiTVXFV0FAWZfq4E+XgWntQVmj8ErYPBmKrGuOCjE
            89mPMfYrsWyT6AOxfYgweXss9vdFWpQmPCWkhhhZV2jn3NyHNmgDok8mY4EaeJIM
            vwTPe/vsBYHOZQVtE5TL31POwskJjfIj3SCtJtRLXvlFH4LVWLQ5m/PnakwiZzKK
            rQB4XlRWPwhAEPSn7X6E3TZ6yibpPSFROvulq00BvtjbLfzmng/7lZi0nEn5AdPG
            Q/zzNqs6BrlLy5HZUyJ81cAh8EQN5ue0+qOqEJ5/UpfLV1e7bonCj6pVCdhOYvjl
            D0+wf3Qoo+wZMDz4noC0HWTdMJxn6hpg6f76xKD619LOCrqtadOCQupdxKFEQAzS
            XgG4c3agVX69wB/XW4ODkRY7HrM5D7NcI3oH4LDwgfzbFArFDldjaE3fWPHJv/TM
            B9lJMZ7ijhkDS2jY+fpPM7FsMZtct6SXl3Tq5Mz9S1aWn9IeyO/GY//A+Pup+jg=
            =1XeJ
            -----END PGP MESSAGE-----
          fp: CC024EEEA2CB6DD606E737C3D15EED89E0132A8C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
