apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    #ENC[AES256_GCM,data:651orpOoE9+l+soDIE+9D8IXUqzZqwPIEXydNRPC2OSzfC8GHshIWjxrpqFtAjxPhrqk6EBAsjJlqMtMh5floygvKl1dKOA=,iv:OcKcYDJ0+m5BFVQQQyNourBAL0QA2htsqz64e1CPM1M=,tag:xfXliPMrIdDZTt7XM6VO2g==,type:comment]
    values.yaml: ENC[AES256_GCM,data:ofydjgzmkx6anK8Vlj+6zXh0qS5GDlmYLwXC064NRMTx2OTYOh7c3H9QIMq17pemZMtsZJBHTkXEh51W9AcglYdwcf15dYEZYOWMxeUwnrcVPucXOTz8JK9U8225i90x4JLGES6wmXmIhG13nJa3trFEwRM3TinqJsZkxrgZKm5/3dmqgtxNxzZFi07Rq9+YOZz85+d6yvNW2BuSk8RGEMGwky7C4qo6AfmyCG0LrX8ecycoBBgmGU+uibTX7ViMu0qhNy7e6oi2k34zjXAWzRWr1ZOV58NbCaBNxoHZRd462hJ/xHhkqy7lZz6xHA9czBatxgsZxE+e04GALq5C6vU2DopY/8EbRBkWnWsVkt52ObxFNSoNC0y2pvJglqOSeIwHWa71J/HsNxyvK4cPmehHLKNEHeONyYaIu/nLDSscN+A+/fak4f/k5u+fH+2vrSR8Ha/3y/ioBU12LVcrMUc6jsFk+Qul95ohDeBYidIhVBUyU2tkUK3cmAPXxtPY9tjDo63nnkaMWdm+V2O3j8iq,iv:nxkwgkmMtpbWkrgbq/iyC58Nt0cu9ZSr34Koj5dIJb8=,tag:KFSd8Qj7ZeRFCZqWE6Q5tg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-29T02:12:31Z"
    mac: ENC[AES256_GCM,data:CaTdRnJfyssnym1Vpp4n01p5qdWO/WheYYb1fcwcUe029Si8FN1zyrmk22jSkgDY2xjvqvaKsHUFkuEtW9F2h/waSqr70ODI+41QvtijW9w9Tz5e/pGPmSOAEYT/t59uHYbsdKd7lvtvzcZmO7qZ5nOA3OWkO6hE6h2E+gISBZg=,iv:VRg+j5Iqp8bgw5A4lxfgrCsULJ8n7f5OkWTVgVOo1QY=,tag:aic2uFOZou/bDJ8PkMlTWQ==,type:str]
    pgp:
        - created_at: "2022-07-29T02:12:30Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0kKO7GPsbc+AQ/+JdyaoAmRXOKtrPvV3UPZ7TJclsK7B5r+dC/8FmtgvxOF
            UlDbe4jmsd6AbzoDpR9SavC8Q3UEqXGIUVtYc7Q/i/2yJUDkk/ORwiceHb8IbI4Q
            7XHjE9/JgzGlkxAplr/AOaF7KTzyrybk1dXuyS+Fem7bzE7EKcqm4CjkxghvzlyP
            EPoaOJqDnofNzkJmuypJeNQ1j/yMOEGGRsz8nTWYFV6bSRRw9i1qf8jdQVLc/xL0
            PckPFML510oE4gVP8coeVto/SasTncUO6Wln+Vp6vlZr4lccAIW4o6H65IHFEG1f
            yA0RBur8BJWkFMumjvYeTv+GzNALbXOmF/dFrf8XfJy1e1jJ1gddAKzDecWajq4o
            oE6/dpRNGKZ5ymVoZPweOcMBdS0G6L8lZHVuqMjKmSqadbr8CMQyLBTdd1ZF0Qgk
            s7dCtUZSLgiOjnjLFISya3NSdr1k722eO3qEDpM94G/5AOfZOIoDU/lxUAtKvWnY
            YfWezlxSVfr1vOCFVYBrKO2PQGIgXYEhJaVnefwoPOl/GMWBT47wG+Z5zZvhTKZ7
            iflaK2gTYEhvqLQesj3WNeWXfzUte0xGF/AUyo237LWV+xf86Pavpq6p3NHgA1X2
            COn0jLspbJ2LH7o7YXnpkqRCNGKS90zAY0jDQIMhJVvdErG+vAkQpJSVaEdNBnvS
            XgHzsDXOGpYOdV7UpvRn7qq6LRHzlq4ZIMHiBp54YNkJ5Ogg/AHvOkW3Vg7lsLxM
            4KmC8S+/C98wC5CK4olAtd6BPtctB29SZu0nRtb+ML7nSF8Tzv7PTZCcwkcAtIo=
            =Q72m
            -----END PGP MESSAGE-----
          fp: 01629CD6547069C70E86E12CB52EFD7E5B007F33
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
