apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    #ENC[AES256_GCM,data:NDR45xfFF6s/j7l6KgQlCCaTdWcFwZYAAJQ4rc6FZRyDC9qxZW7gRRuXzu7ux7NZNl21bLx9BUeWNMeBtSW7TdO8iL0jmVg=,iv:DJU93ueBx1FNr6gTwP0InxW+WHBATsA8haj+QGUpRCI=,tag:21ZivDIhHW2+cW89eeetvA==,type:comment]
    values.yaml: ENC[AES256_GCM,data:AWTST8P6ROklsQJwSR/KR0rgnhaSJKISsGvsxmA9UOn54/zPYcuDB8RCxsrFLzInqdxnWq/O44Y6yWSyufJtiFUPrsWLqv6b5iVl9fE9NJjh02wTpEVPI5W91ICIP0x0xOBQN1BlFw0p9jtpF37BkGpkPySos9ESR11/vQUiw8A61LytR63EDuKck68TZOV9ag4m/K67mK/UL4qdo4qSB03CTsDkua1aGTJYWRQy2zC8Ig1XY2WnrFsyOYaZoDVS0wbAjnt+Bg43HseQ2gobRRa5ht0NqA4u4yY2Zg9C+N40l+W+ze2/Q9BoY+/znerkmlGktFbBq6UQmVNMD0mn06Ff8xE4gJSttjDuYnKezkWOWIz1I0OssfUhg8Fz0u4mjTvTnCcQh3/eu/HbVXJ433LlvN23YA2MEEulMCgNGa3fY8tsdyg9G18iYG+id9JwUtUrjfdaokEdUVpN6C3f9CJgm3EOdEDdBxf1ArK91MiMibHRbLhwz8/1D1yD/9YSTaG1/FSWst4L+SQhn8GGDbmK,iv:sk6CCGU0hhzoqueBtryS8Sr4RuRNwBnRqlQQ1TEhaU0=,tag:HCSzM4DGAm1lmstaAidJGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-02T02:18:35Z"
    mac: ENC[AES256_GCM,data:Kz0tFhtwITszu++th7E/5FsYuyDAG3at9fRohLp+6/iFysDoQVvcWv24SDxSCEH2XniRFHwXMPMeMedIvRa6u63PhWhhJlbH+CSFOzZ6ETF5gp0Kglyb7OrCzmJatC9uPjopafDw6A0jIXmzUkn+iZs0gUurBg5+ZJtETV4QI/c=,iv:/ZOPAIsH8Ho5ZZHtIPS+fDEQrmbaRfr5G+4xtqerS5s=,tag:W22ACABWkTCZP268wambGQ==,type:str]
    pgp:
        - created_at: "2022-08-02T02:18:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxgNVO5Ju3bfAQ//Tsdla3kGkvVrsZ7orXPDGXuUYsB6LMghljGYA1KMm9Zq
            I1GKXaB0VL1Y+cCXR38uy/lHAX03DjJEMaoUYfaBpWrbeJhV1ERYuZy+0LSSOWOk
            nmGCE8N7FzX2J+VkDrr5jH76PYgr8kE1ZykYRBqXeSNZpNtoi8CJ0yQjg2GrUFfH
            LVNHqVderZpJRAIVqvHjDozu29OrJgIvT5X26yeYtzUFpUjGBFy6zbETXXLHINtC
            WqtuHzgiXQNJD7c0kohGdRA+J4o6rys4/2mbqndhqQnda5uQHE/mNTVMdrhzCb46
            BhqjnoEkIh1goXaaRnAkyRSqmyQKf7SZWnw1CLwCSEhJCP7FRNx1Gh3eGT0CrAym
            tMbKZkKG3IAfxpPlWVNWDZ+Dt3//cd7n3OnfJ60LxM68eQNTzKRBDlDgP510jvrI
            QMZ153mNZL9tHjUI8PCXdksUdYAwSSRjH6ANTnjH/a5czq1BoZYWzhbnrUC5/RUi
            h4UYotE2W4tZEC047lvaQnPWHzrMjyjZv4zQuCZ2wUMPUhNvXFI78NlTm4l8coJb
            7w+VnYWTEKpCxktrIyghEnFoI4zDt+yy90yeS3iEhjUfbaXxwW5EuHCSTBnODMYg
            Nr+oRnjLheOiQhsawFLU2RQ4s2GIGRpFdlKgo3mzMFBi5aMj8qZEo67JvrzUTozS
            XAHiHmt2e/c2qM4BlvOqmf1S7lnrRSiRINDnDBKxNcstKGvwnmiiLI3UNoQ9Jc/e
            2flCkC6EgVg0erFoPLNREcL+drX5O2KqGZMLBS5n2FZ3nzda24UfkKmMeYdV
            =sNR2
            -----END PGP MESSAGE-----
          fp: DE3EEE3B84115B7CF81897700E8F8A3856EE5BEB
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
