apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    #ENC[AES256_GCM,data:u4sfVTosvX+lZ7IiMX9mFDeE5+KYr2K/nhOL//QJtqVR4oLP2+9eHGIKOGTte7ji893q8B/x9Q8pBf+kJ9YLM358GWVWOxA=,iv:YfhvmhjkT+kMPPgFLxxN7069+IA19+yZ/8ycqsGzvMk=,tag:50PA+WZijjquo/1xvh77eA==,type:comment]
    values.yaml: ENC[AES256_GCM,data:zH3BSRVuftEXAyu/GI74Q9ZW7+S1yzfFIrwueZ0dVWLotrOBRwICyuF8+PujNfvd6paf7bMmre3FFr7JgPFOaJzw1uClm/VTIQQYv54MQapxSYFG1rvHpwanOq9t+9ItSgcfBPMAYgb18Fqqy+ufUiWReS07+Rd++NZbNoh1NcTIgen5RoXx0ha0NpZbhQoXTUd948xmksY8DvR+vqD0LgjpAzriHt26/3xuJwkbOHyi5k+BourcXivQisQcUFVgsW2GldWdqZnHjcDSekfxSY0e5ZrkmUNu0z1TzWTxqycWZcn1X3vvebNeJ/XYNOYpQsx79O+qxlRGa1qfql+iS1LsF/F2FOjPZO6/u7ALPSqWYMolcYW8xoZ/gphliy6R3U8D0IIJGljp41ZOGrUfQxRa46z4dhaFelZgDOUtbRvCnnc0a0VOOixQ5MQgVuSUXHqaLQlex3r7ckv1Yo7QbEuNJO6WSeC3ZO2YQby1X7jZA0+G+dV6lXi0gQ==,iv:z9Xjp6pbELu0FOcHTMyVBOU2nWIz+G40lqQxckddZws=,tag:gxNQ/sLNivhRSCQYVaPZ1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-02T01:10:26Z"
    mac: ENC[AES256_GCM,data:Q1iCnVFiQ7yRzj5mcqCUJN73z06H7ntkjf3+b0OAh3elwWmhHrfEBx4R+8aS9dDJiUDOJg/X96AIWHiN4DlR9azAO/hAT/fIomuD0DWri6qXpiYkNWiIGQy6qKeJ8v7gr5wo8QNsxhE9J7Dwpt3aC4xRKq3z1HfnC16lfBZYHtw=,iv:9kYrW0bHnnXF7j96E//pYk+vDceObNXSY2BXVAJdivM=,tag:Qm3DmirWaFbL/tV088K23w==,type:str]
    pgp:
        - created_at: "2022-08-02T01:10:25Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1oKmV1q3LdiAQ/+NTgc7kQ3PjHnYSuqEfvRvahAnY0ciJLhtcAKo5EzoX2v
            teC5RnNhgAJKJNYoal+JmokFCozrvr6ib4pK40RVNY+lA48grZtPyWl9aNrXykoJ
            6UVXQvLVSsHKXH4WaRaelyLsIkj6DZboZwvmgR8FBcUzoap/Mc+crclwnnu7iQ1O
            c+aR0k+7fZ8mpX3hD7ZtYywEi8M2uPonhqDKyjA63qAo5NLMvq92ePotzRcSPhxy
            VxBl6QeagzyGtEgPavyFRRdV+eLeHMWt1pivox/nDI6Bz9e6VxE6ZMricVP47Hsl
            ojKI9TLn4Ns7Hx7DuiZ7aO76OENhKHymMJHLza3R3CuJYNdPdY6Ex+/SGHujswoi
            1WUMVK61yfFcsVKGUc3sHEyjSWtQqo9My5sx0Mxa9mEA1GI+oQx74e8IWnp3HCOz
            94kEsaye6CZlfYTn/iC31AcSC1RfEJI2POnmajcJfj2j+KDYmNUJ3tKV8x1tLMsj
            EnD2+ePIxskT56kZJVn2eoKmTUP6QvYidwn1tTjnL2jSxA5sRRmoNNELlPvtKiMf
            EYDTSmTCzCvF43JrX1K5ovv0RCbU0jHFLy1X/iLR5U7BmqBq4WCxY9j1f+m+mZNs
            57bXhnYfT3Xb7xZcyu63rGIo0vQRsgsaCzHSoZnEenGapI8M23PZSSfKWm7BsDPS
            XgF9uBY2CqUnmnU6IOh3t/68DyBTZFBBhQZl3Fc/iuGYohBYk1oAOmJ5WqFUwz9e
            uwirR+/GjhFv05ywXG6xQ+SO4+1a7yGrnfhysvsWZrFcY75VfIu1d4XnNwuaPeo=
            =rpcD
            -----END PGP MESSAGE-----
          fp: A352F19D2FF3BFC1E1A4A23E89228B736D168173
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
