apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    #ENC[AES256_GCM,data:Qizy4VU2WbLo+3qk8rWwugUd8OVqdWJ6CAjOFIrgbq9YN6cdWAOSHkozaS0twxcJ9Ul1z+JG/z1bOqd+oHEM4cc8SBmYzJU=,iv:R2B+SrA4dK2fE0Eu9SwiccYg12FcjFnHkkxsl8inJ/k=,tag:nAia+SWne3Z/zTcI+x8CZg==,type:comment]
    values.yaml: ENC[AES256_GCM,data:mxJXTlwcvEwMS/3Gwx+x69bSMD4nbP3woZUzxAy5HZjQQ9RnfJD5uTlJK1fypY6NpNgqkrFM6Mc7AbBN4qYIgG/CJRInZyL9XXotmHA9A2hXYeDMqAmSnU6VhrE+0YIxXlLYu8YNh9Vpt3AWACOjimJFIhBEDzw7G0HcMSHUCInqEbAHmJjQB6gfGgZDSZ3yMCMheYhvV5rDBRRxsUoHZYJtQ+xokrVm5Jk1HyztQBKRHhpKQgfjO1tou9iUqkQt6OAcN8H5fif1BaE4/5t2kNEktWPJesMInp8pSjUAweUdsQvvPu1PL24q173YW1Re5PDFZhTUDvoKdx55Dkobf5lJulbPprY8mEgOGI8uyiZCpbEtEqVi7/WmgfmlhOW78U3D+j01hKyFHQUlJhGOysqZ1w5U9k7+4lyWQIs8GUh1O8DfOgtRo6eW2geMBuW/Fd5hzovFL8dkkn9qo82z8AOq9yPqKGWAiut7o+eJtqk9e+1HqfUaddM/jfjWtUu0DKQ9q4XB2GyWMTtmKy1SInH3,iv:pv3Z1aqT8m7zNEwif0WycetTebXscqc+cBSq6J7Yrtw=,tag:PuDPoi4ikcOwZ55F7uKAJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-28T17:47:01Z"
    mac: ENC[AES256_GCM,data:kF5uH+jZNl76AzuAB63yC2nXiVe3Ynsb5kpEmp+lQmCRAREO816rVNktvkGdq5j7d6zz5iguQGgsjwiJl3CnKxtzhT3xVNSHhxM5tV9SHcPXS3/wH8BToHnaQJ/K6/50N1M/z5mR/WY0/B7hhZLQ4YwPLY4q8hfNTNoW2igsczo=,iv:knqNkL7PVp5YsJ+LgRL0evjB+YA4IeSrtFclSwW6JxM=,tag:icvGBNosMKOUJPBg7oyZDg==,type:str]
    pgp:
        - created_at: "2022-07-28T17:47:01Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxL2dJVh52oKARAAyxsd/+DM2Ut9cYJOhBudualQq7p0kNj+CVPlK0Cs7FWc
            ELyNI91kMg5U92HUvMHdzQsuENbfYoIMcrXBfpryDJLcN2dPNKi67UxYi+56RHh0
            39V1iHFVouNUSJeLFL9lGxKnbj+xZbYKum8kXzfj8UMHTFcf4N88mxl3UqcBmdCp
            adoViFo5gtqwzX5zGB88yvFHOJLRRyU3fGCZQ1Jx+aNp1OHlADyvHlboPJwcTvCd
            0a+Dk89T8tJazwQG21evO6ON8d8PuHJsuuSGuD12iXqvBYYFaOLCJ0uUmyXFqA8i
            98hJ2/jgRvS8Y7UW01bRF4s3hDEQyFQbaHGclDbP85IrG1Wk24W++H5s8kjzS7MT
            UNsZ4VfcVtDaLEzFp+Rlv34v5NOwbNeOUDfkTU4PdROHumymWwcEN/UdI0Xrt5t2
            ph+mvTnS664k4u+RT5mWUQrWnF3+ui56WgCG2Zo1scKUf6klBIcu6dU61mgPXR1/
            2Lkx0ybw0sgbHrn/idafEWiI5W6jQWGQSvpma8jEHknY5ChlzxSAI++knsIcyeUk
            egdwFKtpGbB2oc/0oBkVjkCVOrPPxNwyEGzXcBz2TIG9ZgX0iWHrs98gx2XaccJp
            4rndIvYjfotBJcTAGp/x3g01qUeg2Du5AzVl0fWrECuuDTKZv00zegT+Kzk7Ts3S
            XgFicqVBnvu/uWM7l3tVD3Pws0vE5M0gbap3Or9ZS3HeknbR8CUPU/hXN6Xwggg8
            uDl/DqpcMszO2AyRgq5Ps7K+RTOfvdAJ5pYPQgca3OEMFYlMrJ2N88ZlDflMVjg=
            =wM+T
            -----END PGP MESSAGE-----
          fp: 3A70D5177284887695716CB707A358FDD1D36476
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
