apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    #ENC[AES256_GCM,data:LLc9ehx8ioLNQsIp9vQXla52BM5jQYB/o98kBy9TF1C5Do51KZdNFdo6Uj+p5B59ZuSLAHGba5n8HKCerJ1EU16oqOMDFKY=,iv:x6vVIdNIHfUgLApoa7ZENUVro7AzwnHqom0vjJAoekA=,tag:Asae3qMJXpYsTejR/RXxuA==,type:comment]
    values.yaml: ENC[AES256_GCM,data:bSu5hKNsLU7butFx6Qgn37MAiHu4UZFjQZPqR1Uwxbj4Axx8wldMdeEvP4XdQDWC3t3Z3h0tjZQ/sfDMRDlAS0JqmRLAWmPCA2nz6uQ8dD6tTVh22IBefADa7S8gPvhrB51pbgx4lbemGyNWGaBhlWvh7jbrTtj76DMJ7USGIRCSBGbh9e8lmOirkQBNrO2G2sRe8lISLoDYMv5JkKvCIaoAqXd+L4HeOqpCpRdEDcQE/XLkjwwn2cgqdJmwoCK+eot7C0T/kg6qUQ4UcLwlvJq0iDB42NQ8fuaalsbZYCVJGQ7WWWdNE8rFLPthZk9FY4wAoGGAsgCj20PFZPG1Yeuubw5yAy9ODyuUhc2+6evcpk6yaXGlyRBgB2ysBtcFWKeMirC/9hXLHbiS30d6QD0Z/rYCIa3SWMyMb0DVqcD+nJXNDGHW9ttf6IsD0yMyLM5gynAWy2HTVZBfuZZ07B25A7Yp/LzWUqsHHFIYox8bLP8OQ/+KyHpurQ==,iv:iw49evTKjnroblvIMagvWRUqPw8TmjuWib8z+MHrNhQ=,tag:NcolyJhofy9Femm+insZUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-22T17:26:01Z"
    mac: ENC[AES256_GCM,data:afIxw0AfImKr5eO+8yBzPbrEBwFdoQHrPKhQPCygpxQ0lO2STr6KD8fQAvStsk/v7mJ28IdV/3MeaW2+MxYGyOkLO79e3NGcrIYoFpM2XGY/Qnh2zLXZ2v8P3Cy0CEkp7bodGF3gaQ8SxREWIWaliErXPWcjp/XZqVVwWg5UMuo=,iv:Y/Dc4ewUHguHWEuAjQR4UtjTLgLySdQeUSylCOpY9Ec=,tag:Y+VqFp57tuFMs59ju7YYPQ==,type:str]
    pgp:
        - created_at: "2022-07-22T17:26:00Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAz9sFfeBl47iAQ//c3j4qvr+LxcB3V5P56qefXFIJwFkaJN2CkqSb6bH3qWq
            cHq7/+NpEFzBbe5hHcoxHT/eWTIlP3HC6UVQg2oUA849t0Wy2cWdVtZdNYoxYEUe
            0vn7pORnw/XO8wUAlMN3yiNy6HfCVoslR2OBa5P9HyNJE12jJk14Cz337PkBJXC5
            8DzjjdqAJ94GI33h9rtiD8fPqVVR9/9bMCP61j6e2QHSuNmGlIIafrg+3Bnzq6pc
            D0kzQQ/Efbz6WYMeTNId8J87fXgj5Ezw+W+e7umCLdWh4y5JG/b+Cfs0tam/e6qy
            W9UeGFIk4akGoFbs+DmzJQL1kfhdn/vDP0Aup0Dt58YX9DGZv2mm+ChsN2GZLk4O
            qt0kyVHKEpxeZ92Ps6BsqVzSyyJj6GPXA5cTwZr1cpm85ENLUWshH63d4VdD/Ubx
            mSrwBkcR7EfSBcWuFf4VfkpMC8lNrk+k0GfubFdiGL9Hl/eNQ7Yjjk2QuVaPK1dd
            40tZKjh1eAqCfxKb0y5aBUwEIeHcv4gXSsbOCsQ8GoOxR0Ivk5yuhAdYxn2oihyg
            Lq1Vv52URvElwWWSjh6aoAz3znau0j12nQnoom88MGYJDesBPVjJkom8+XekAYmm
            RN/H1sYnchY4pZy+7mthQ7SzwL7EURsrUS17aQo1D7AnBJj1VFkPa9airU7Cq1bS
            XgE6AE9hQx5QrbhUeoLtPFd+8nwtFgn+b1zRvvxnaeThWQ/yOfRgMAaMP3wmr2Cj
            tZEUv6lwOtcN66GRinxiCYow13SXuMduxbhu2orNE6MYpaAGnHBAZn6bQOyzHzo=
            =8+24
            -----END PGP MESSAGE-----
          fp: 4722F7B0F85335FAEEB4F5752406E3459CA8B3AA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
