apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    #ENC[AES256_GCM,data:PXScEXXbjEN0bJOc39PZK2fdCwpc8/dU9604tWKTBrEiu3YCwbFnnpZ7LmsneOejb8hRoiFbfhqh8F97VBqKSTC8/17tx6U=,iv:X275OrPD4vYYBopZb1b7MMSIRzpdbImWlk+uPoghxD8=,tag:hQ/Wh1jeKlqu4V4xhENpBA==,type:comment]
    values.yaml: ENC[AES256_GCM,data:rX7ABBf32I+fVup+qd4SAoLlmjhEX9K6RkMCL0/2FyP1t+vyGAGKBZNOTDQld9C4tUXhmPY8elZpIi8nuR56bFzbVGhMbzc0RtwGLdv07u9E+tSfmNTL4tU7jHPYHN0Jjwi4mveCRRmwOzZDTA2fD7kd5SgDY1Xj8mJWHSTF/YjJXAr1D3CCkwvPAPnTAQ6XkUZT51kq/xaNTzYYF76EQhcfeXcvY4KUlFQ8rRyDPtLhTZH9QcrPRTvl3ZtAUELXcXeBFMhMjmgv35t0x44aMV8KIHGxqofNn4JrcYDu0d9W3AUGvg7hGwX3XL9auWUJ7w9aXe3ywI2pVMV/c68SObb6oQsX/vJmE0BKHvxQEydTDIFqvem8P1fwkOAeB9xMwuLEG8bpxzJK/nvtVuAxiNEQvYqttU2egiPzyUK37syLNFFAy4Egw4fQS6rhzy91iPNRj/dVaXgtKzE2QcWvOv+opdrLlqLig5kozYIWovDJ/WCytC4l847Iqw==,iv:yMhhOAsXSoVAFxhCJn1PDbR7LD/sph/WrY8fX7Uh8lc=,tag:fD/bSzaHTDboZHlOpRicBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-01T19:21:15Z"
    mac: ENC[AES256_GCM,data:hfdQwJXXWtPnM6qDBaE/dmER2bwygWLJH2YkhecWpUa9jSCrZP/9j0Imn0ie14I1lvJ3aswugOgA+YdyoXucSpg+d/cMlpVH6hdja6qRxS63yaM5dwzVpaoGkGB5iL8X4o2wFbFFrAUeRnVnvEMLVPvKcGza7PlmZqbDpINbctc=,iv:NRPp1tZlhxeT50yybb94txJuWJAtRfDSGlCX+0vlLuY=,tag:ZqbBpt+GGAXxjUHB6SKGsg==,type:str]
    pgp:
        - created_at: "2022-11-01T19:21:15Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6L1dXQ2YhQYAQ//Vx3vgYiocPFXVoc/+qwv9w2M7pS+h7SBG2EsXe5FjRE9
            d60Xoa22h4+1nKLXkk6WvU0AcGGok9LS8eJbL2ONlZdTacMSdeMl7d4z1cJo6+Gr
            loQ44H9nVHrPdw1l0LqD6nGsDpHE1fYwE3AC0HzaQlggQ18OJX/Z6e0JDJs7p7/Q
            3ShJX7WW3QLWHKMMTOHphZwMakWEQ4R0gxVClxoOtLeAkGF8GekF8fwZaOKb+ulv
            YrrodYROuzYUcLqr1iCFIkzlKzswRjvAvMS9eU9UFOBYnA1gV8uabIag4oBxD8Zb
            vfoOOkb1A7NpTt2ShvxPGvy9//HuCeuO4nzvN+j4GT7aC9QVd2k2v/YgbWeeryek
            WmW+UiBVm7EWv8xJr6ID+hS5OIadR38MVX+s/NZ1waiCUP6j2MRfZGzVtiaoM2qQ
            fF4PKYmRk4yMucOBWIWrJTvlRN7O73/ubxeF2Siklpuddih8Zn4Je0aGjW0TfLoM
            NEKOttmQQR6b/QpJ/qvT2l/Sxb6oX95sepgFIWY7a9ZIz78mtR810gICnbepgqC+
            Mh40W9wy8rCwyRJj/OwY+JDoGOzh2/pB4YnkCL9y7VFFXIEDuuJTKUhAsyVkeCGQ
            j2GJv7xuiNxgR9XwBPn0McpiInTuQ6g89jJ/rF/QQ2Rvh7BTARRCFrmTNv4IjnPS
            XAE3CSmvZD9gD3zBsb71EvjXYJZurQcHpNQguuU+l6Win4NrIeHqm0xnEtcWMGVj
            MAYocBa1LJgWArjre7S3Oc78645smAPyPxGpJRjLYM5QcyINnH6IpuP6qAXy
            =RD4S
            -----END PGP MESSAGE-----
          fp: FC3E808336ECB0A2C80506ED0AB79323192253CD
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
