apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    #ENC[AES256_GCM,data:NIbNx4kyVOkSkzGQCGsrcf0dsYT3Lr3I54bwhmGK90gpObXlD2haDoBze2etVspOc8msGiKF+yEvgva39m05rcXlUpxhwXE=,iv:N86jMjuBUqYyeP+DN6rO9CPHM29gGs8hzJAaqFb/OM0=,tag:n9RfJvTeeuPro1wqbYLTdw==,type:comment]
    values.yaml: ENC[AES256_GCM,data:C0dgumGqeRdLPlQOFHx5XVgWkgYRZedytC5N4sZgoEqRM2TPn2jio/NRaQoBldxaHiSnQxWlLT3SKioxPaKLVHjphLQEHKmo12AeCF6w/a6BRU2AeFWZpL9fKX8B4FcQam63ML6GGC7mmT9UciX7lTteYFanH9PK+mOIgMJ1FfKf92e3kOsrv8iAzrV2sf3Q0oQBFj9EsEcw7lp2WRMpqxKoBjDEyKl4mWwiy8jz0YZXdo1o8DNsiIBMwNCj/airbJQeVVvWbTyxEEM6oCgnHuQC/vBaCN3rxI/hiwdDAITz1QIB/YAXJbC4QVwCYL26NaXEk7Sryr70S+xhpKbb7ju7KDZwIU3F/ys7vVaXhFBLNp82X03HiBqMGwCVmqUv/KjiPSdo4eS5Yn0X30EDeiWZfWFGQ5+BR5FplEbfZimosuAn083o6Zm6eaIql/ApXNf7YKl6b0tWBaH/p2/d8Zcj1TFVX7Sm0m1IT4vD9Jk/apes4grOZEeGQQ==,iv:XMXLpZFP4IWovkIjQJ4qAf/2QaV6yItlTWSN3DMc47M=,tag:CYG9Sur22KmApoYheiLxhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-20T17:31:40Z"
    mac: ENC[AES256_GCM,data:nAlrJd4PkuS9by9s35BQ45O5u7GrgEiEXOMhWM1HkblcWpFPZj70SsFjkpVq2Paq+OUem5Drb/vF+jS1i2Z5aUJVOBiKIxZ3ZXcqfQrntP4UDQUgLf+K8imNt/4EBjqQ6vPoQYBWzTEHQf50LzZaSSVqJUVaD2HX66kV7XEaE3I=,iv:o/2rVqUGbLSLpLwKnHbAUWdeq1DwRgXSKise1RBedxU=,tag:y4I57rt4PCGLloXUE8fspg==,type:str]
    pgp:
        - created_at: "2022-07-20T17:31:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzTICH7tw6JyAQ/8DCj/SuPOiL0rcn/nGACbeZl1R21cmdZX048BqhnhvMO5
            qFbZFu2FxkBXIlldVZYij9uzId5kAP6Q6xS8jdhtxLWByQ6kNk3wb8SPNBw9m33K
            rsUhsDhEWRPl03LVZFNdg8jqbkL6ju0c1DmBeU2YdkD28LqQ8lL3J8e3dXamproH
            pm/yRWLmFjlpW+bb/urdpgQS6jXyf/Si048w/azVe59qG3DSVwriLQlutxNu3x3E
            04mE3+nCCScwIWw3OyljV2a8w8Ws5ov3WETubSapzMuQxQrKmbtO+1YApBdiVdyO
            wKxXMVdB6X9OmfAEjWHZAJRSEegC5lvLC3LN50bCS6UJykbfCefzx0uSwvgIxZxb
            De/gEy4NAqZeO7QINS1RC8F9xPlmOeWuEOpKripWlFTs/6AvJqGOvTX9rUYDcJDI
            8Ml9H2XbdMzImT1UjQhNyLPfeR8ODK48wFhxuaBFI2u79wqSBJ+fneAp0bTGbnh9
            go+dB2Ppb46uNFJy7ySmchP6A7oh7OXSeU2vdYRMTD5Ercn8BVFKM7nzKs8pJDsA
            caSboK9ftv/iGH+jmzDQu62c08xDpk7wXVWOxWJ9EjBC8BZ4BGgMBmb+Mhl6mQvo
            ls92xeWgqIX3tj4jArAhfc5ZJGedxRXXxxK82gUXbMQOMtN3NUYNulqwm7g6euDS
            XgEy9XQgo/addx8XF0zFQC99dha9fcISP92/L99MOstFwV20cYi4b6EN0sSv8XK2
            oLAdZbQgE6y3Wia6uX6eZAZDheBnfWk6wzfv+WdsF599FHv/SDyhqWXCXUGl5lU=
            =A3Zj
            -----END PGP MESSAGE-----
          fp: 02E9F42D66181F31C65AE49A2BF4679927DF680E
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
