apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    #ENC[AES256_GCM,data:VNhNOaZlfl5B+lAFllTUFyIwXPpAr2cejVIlUIqNnGAFYuHhNpBLMuhF0q/CRt1NNde+ew6MUHdsFAvV35s6HFvmEYcuIJs=,iv:4zV/yFNFPkgpPhGvQizkghT0Vv1U8ZqE+NaMsl/rbUE=,tag:lotkawulPr5n/BrVw61trg==,type:comment]
    values.yaml: ENC[AES256_GCM,data:K+YieSzFBi4MpjMwEtlLRvrVR8Bwr+1wr5V6nyUTI6oyvlgLMZlS+uLJrqjs29HQMa2tfNpNCXwneRb+eu62ehjau69n+KLe6rLYWPiasj55aCPNSDAiJ9nj849SipfGWDnownU+kamUwdulko5XCTSDRhm3XRaU20yNKTGKo1xoDHfH/+ohmQS1EKwZW3NJt+Q/FdjWTX6zNXDjhyNzeQ3yAArmHqikgd84lFHeYm+mcBMyjmIwirQ+3/10p9H4vH0lB+Vo4MtkDiMB9uz264AyktGTkueJV0ppPS9hLE7MSufI8l1t+6bnrTIh1/CzFdyvSzG9sl7nB34eEO/tNIlr8ycmyBKi8uDIeT5Sjgt1/b03YC5BNJhLNyNhtl5tJ5r90HjDRNg3xK8DzkUfnnHY66GmfTk0Lqh0XrsqbYlnEE5bGmBCsDmu4SO+axcb/OD8bjrhpXGxEQb/QDm/k5ZHIODruKrhIe305ciwmRC2ViYFtaGSldBpvaVGuiw5DqiXzmvw+ZDEMrUuIkopC2Kk,iv:RZ9YUzj2oPK5PyBbP17FAFveXpYqQn98dA7IRlb383g=,tag:PY4PC459olcCRwKFmGtLgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-16T18:39:47Z"
    mac: ENC[AES256_GCM,data:5BrIPy2LaTUxK5Z3SPs3e64VeoZ5g7PrpOP/bqt8gUq96/lq2qy5f2h0lOaNqRhlq8e0XdkB+en6kMiWUHjGhmIPihMRoLGmcmDTjj0uOyGQ8dEK1pItoBQ5DCflE1ShRj1GGAmfzAzoHzj2bLLeAuDzzsfno3j5LxrgYZb44oU=,iv:j/Keok7OZHcyViAZoGigbzlqR3WvrtnOYLMQhD1Te9o=,tag:MeZrhdvoU8aqivZw/xNcAA==,type:str]
    pgp:
        - created_at: "2022-07-16T18:39:46Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzT4Ljfcg8l5AQ/+Nz7lnwM6+hq3svkEJmdvUGyJFy7UL3Hjg2yuEa/yMnez
            TKo9KI0ParkmDL+eY0sV49Qu7LYGiQ/ZZ5fF9X/+nS7vDRTU+kvtx01cWCtgwPA7
            oidMCnTLnt9aLv9MTUk4dEJ1rIHPVA9KT9CDlTVNryT4ufZHCNO6vcpgOlMC6ncz
            tfLtrmAZN25vnOmmsdo5Z8Fvg3Y+mgSlx824BGAZN4fX//k3WGeh8uHoTYmUkRfx
            tDuesD85a+Vein7xlDE4R06JiFGuWGrBvYy8H4MgSumieeBvT5GY4wyy04cF6lI0
            1VZZT+zGgIjdLkx+WZ7/m912ufpIxdzbVyQBp/JxqdnB3/lXyd0WXqHb0CqcO7fx
            JLRkSyG9FX6xrPkQ+lgUVdeBXXnD0KWQAP51o80BtAbXCRpcL5ijA6jV84dC/viu
            OfYtBfFwcXfSKh/TdlhrzQBsGdLSPwEHg/pPsx2LA0q4lNGc40AtiyMMOYugqsCE
            ty7T6DiAobLou5VsGqccs3SWW9rNVtscjQVE/wsMIz3B/PMVqfr/5A05Nfpctw9q
            apN1cb1OT2Jq+8h68gasg1lLXjLUA0BttGha5YvaKDulxFwQYdpBm1qPtaY5dfTq
            XcKf3sSnqrLhY5xJn6auPAgqkormZuTVWYGuuGmFs/gLSiWnt4cUbei+KplhWdnS
            XgH8vZdW1rwRBoITrm2yWsLpJTu40rIBOtFzcFW4+xTizt1ygTibgPFRuZqI1WOm
            phNLCoA8wqhwU1slmKoNeRjCXc7bW29m2EKWmGw6lJQQE+hrfoaMhMzBg52V9Lw=
            =t8u0
            -----END PGP MESSAGE-----
          fp: FF7D9A449299B40334E0DBBE6D5091EDCDE7CAC3
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
