apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    #ENC[AES256_GCM,data:TEmMzK6b/vINzBVe89BN1OhPwR5FOc0RcysZJpeKYphgFC2uZRqW3JPmOTYTIJHWdTAILvbS00KOC2ORlvMyXQrhKUg44nk=,iv:71N/mBGHrWHNXEnPy4JXwzkvpjNQY9Ffwi56Ekpqd38=,tag:Vok4AfDDLi7WFx/ewcFj6w==,type:comment]
    values.yaml: ENC[AES256_GCM,data:VpVeOphQednMtgaJTLI5pEFaKIEVxIFc1S9NRa0Gv4CX4/SYb7kclAQdhZnJnpJndNfWAIRyloghYMiQEhtrBEdoJOqRY1jCnlDmdfbPA+7pNRThh8Pta+ICaEe4ZCuo2MBxhNQRHepBcwK04FsoLlh4YapefXK/mSpYj+Dogp5ibNVk0MUa+hgQhRdkZ3tl5KhnCbgZOYvpYdZnt3+LX/fseB0WMLP1C1SfP51SQLS2LXlxLSMTIR+vN5hgik4Ph7iiKQgJB6noMEtZYXsr4zvTgA9Xv7aLVIHKM04ZwEHiCSaaiSZ82JQP1EHI4r8jAhFDFm+GLCfQ4EYRrjr6MCe6yMrMd5uoVLTV59Id3uk+OW9vfV6jj6e4m7FEQxrFOc7jIhEggI1XXrT0WRHIvCowb1Vh5Uj5Ew0N3hwih7BZMr8Ntex96LUdmFMKwXUz32Ia5BV8xbkL3tUnK4entv+Pbh+iZ3wICMn0O+aHv4c/gRaEHmPpRouLo/AUrcbZYdrZJmi9Rzyd/Qpl4PYzRkEi,iv:K0YCZKgQYPciPZBRUutRwBKC1+/MC+vxVEvYLfb50No=,tag:Lp6PIDaFS9tDOGByFzhI9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-17T19:05:37Z"
    mac: ENC[AES256_GCM,data:dQQA6W+fKUVh8qYGsrpZoCZQNuR1px/6CnCMY4zrZjMslcK2QpmM3X9sfh0dd5bNEKxa9LUhOl0NmOc//fpoy6xPUBG5biABwf1NtT2mSiZsd/Ms0qv3jECLOOXURGDOR1DcCIfHnBXQ2z3VbmOUd5dOjAb0SUK46yeylGmhiFY=,iv:kxxrU0l7sYvOoaZk/bnPn1hYBHiMbL+7gXlw910BP5M=,tag:3obKvRfSTFGck1Hamyf+CA==,type:str]
    pgp:
        - created_at: "2022-07-17T19:05:36Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAw+zBLqGA09fAQwAgzgBlg/aP8IxJ5d2sFY4/HZhpMV0JienJTbGEpTb250k
            kM61ujCdjKBfpzsytSsvFXQX2yj2W5MnL3RDK1mTB9njasKp/pEoR9siTvtdRTyE
            Mt8qBgTpmW5IQ8fe8nHMm0KFLVBCQZ29aJs5Feyiiibquq76b2pM1oO6fCmBROai
            ogqsuHrt9udT5ACUwGG+ExaMuKlZjL16wOKi+jNgWJ8KpaUF0C8PAoTEiCv0x9Pq
            nwh108saSXxs2UhoX6u5nAcJFDrvfdBlKqCduefgmwBczcbcWPhg1+3BANoxDYx0
            gsRdtjxAsxsPIs/elvxbQ7zi+rdvgZKLkND2oomTP/VpSp1+iDdVxU5r6HB3okgO
            W6WG0pP56hZ5VwPIdsEb/FwsohxhsatleoywpK4NpDeXvwnSQhf1TsPOWfpGOhUX
            F91LQ8r0pOhGqh33xUN3tCOsce27/Ol863GlWkzJuBSBzqkk1oa/C0oAn+db1KVB
            Aw7eni8xu8sIgU95Mmvu0l4BPYsWR6bADc/7cmjuHaRCnS8B6e91OfF/Qw0MGKHb
            d4acs8MWNyZ1VsnQ3iOjbweiVEGFnaisc6PV3+1nJ5fRGJ2NZqMuP9mdjg05FK3a
            7zzxDhqbZ/SflWMBPNOb
            =Bdkc
            -----END PGP MESSAGE-----
          fp: E20408FE975A50629CA3B8337934183CE37E53C1
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
