apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    #ENC[AES256_GCM,data:8iEa/fUXmE6MRCFzaVORE8cUW5rOYCLgku03/LL4szDvjMKtspzK+g4l4TIQk8ZuzROMzl58Jj3S0x6woh00dV0UkDOX0NI=,iv:o/+LZLWIIJC5P0IFUO8CFOYVOPgcrPF5Ql5EO0xVFjc=,tag:VK+9XTB+lg6U+zpdfSWTKQ==,type:comment]
    values.yaml: ENC[AES256_GCM,data:XaVYs5f6zr8bmaAXvNWy+kbuL2NKNDlAuXP/p+j9/vxsaFc+yNzkmD8FhS5UmIwcVN3Gct6OP7V8FTMFO9Q5yzM/tI80SXY7gU868HYx2Ix9uaRqHvrvO6C5s0CaU9T+MQ2raG4ZlJ9LZ3HlBLA6ZfN4xHamkqOFoqL8c+dljGgYkrvSinAJKPvCfIPb9qjffYFJbfusFvQ75FoYFmWlJ226aq+31pG69P53mDpEE7/BvLD76qm8OnBqfbSyp/9C5sOnkrv2oEO3/evkJq7EkygTMvMzLhZXnEvo+e2bsqa5/bFMijo/uPRXhlyS4gWwU3jfYDwuhuPb9cO2r6x4M++NIe9BM6qeAJAvhwWzrXTGQklFA154xBiqP6r20lqhoo9ojBQDhNjdED8Db/Ha65JUeJAYX/L1BERQ0lXm43TuGasZq+GAV9N1hKfcvPc/XQW+KCwJ+jMVGyBE82O1Uo57FZcRBQiUOWAc1uEN7fD4wwvsx2ZkGZU+C5TFV+hIJODCij9DE2Sji/F4AWtGQ8pK,iv:n5Cs3DKs6GnE2OZTM4YSvoB297uASst241yOrzL5npQ=,tag:Bg3VYSA9yhbu8/d8PZL9bA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-16T21:45:43Z"
    mac: ENC[AES256_GCM,data:/DYyyiRPWaWpR3eGIfrY3nLSu+vPYOMg4t0ipZ3GOZJnfaP5uzT1uuxczZZT22eO5yLL31D+U0F4yKKvksI+LHDQdsxmS2XzR6MrrC/uOVsHD7setYADg1DdXMThaNcbOW55gq257j2hpzIl2JcV4Xmio9YbGQZq2AFMP9rMjl0=,iv:UuSNFP18S726Radq4NFOY5Ki0kwyuv27vhfFUSJQ6zg=,tag:nx++6bA6nXxrfuelN/Sv/w==,type:str]
    pgp:
        - created_at: "2022-07-16T21:45:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5nNcjLH7HoXARAAgPIdEAdjPrE5+RO8py+z0YYuRD10f80q0eNOTaMms36A
            1oKZdWcwSDlWlMwA/UwL3Rj/fLRk+HQGx8uBZ74bkT7hibzReR2raQXh6CidB2XD
            PId+R/K/QQGcu0OusffihZccqp0KdPZbRvu4uGrlRdIzQlCq76eHvEViEIlXWL6b
            ujPJYr7hdBtfnf+4FGUUlqRoSxbJ0NP1sJANhnNyz5CYsm//E+r71GrLzJwbdH6X
            xilRtXFRgaF44y1dDpBwRZvi2bLszy4hndPAQlpjSsgGtvLHloiGXYPY/5J4wGvj
            ZHtdO1dv9tkbFpavPq444zDAsUyUq3rE8aOhJi5+YXoleV9xuSuoba4HLxp17BSN
            jl2K9GY7IUWdY8pmzVXvIWHgpUf1/cAkRYNkIUQlnClndeAbMIKJPQNhLrZQEwxt
            SKFx62Sz5jD5/nJDebBmQkmjRE1ihmD8LPBVqb5F6i9avF8M4Tzeox80riHCX2hx
            6GrRlxZdvMYOGC9a4gHmRloudSulSLX2U2kth6rkfN1UtlErmfAaHCfpkC5ou5va
            iMntQRedE9BmiVwzohbiWxuSeCoiA1FXDtKA2m7JSpWw7YSEH+F54cMV5EgpTYMF
            VfcRrFOPCgEGKb8SVS1cJXIIaj/3qytH1TqcHzWoOZdO2TWwae3k2cfq1qKP947S
            XgF2IsKH+CXeyT6cwqFhjPupTLsZkKVY89c1S+aYAKvq6+Us/ZfO+Pk8XOkV0XSC
            ENnMGRXGluf5hA5FZZtVBmCEgR9dyNxeL/fyGBd4Ke8yIxdUFalmA1Hb3YFryqE=
            =bUPW
            -----END PGP MESSAGE-----
          fp: 4BC384ACDA2C214C0FD138A7C6153DEAFD7BFB24
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
