apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    #ENC[AES256_GCM,data:wG5JoxUSm/5LpPWS75hXPe1pOqIq+XrZJA5grzsrwJw2sQbUpRJNF8DZuwLruIXAXuWUzztJMOOVlHnsyCUI3L+m1kIZ+W4=,iv:TT1thO7iwYWpg5EPm+yvW+VPzfR3D5KmE+bPuJYpwLY=,tag:JERFJZWvtSeSULCACxzU9w==,type:comment]
    values.yaml: ENC[AES256_GCM,data:DwNxy5vPmvds6lkU+vghqmrLmWrEJBEgBmpIfE/HAROlNAQs14adQVrq4rYHJw3k1HslKRIJZsyLgLTEZ92GvgNGWSKGMmhw+fZ4LMgIPvQfRYyXW/jMllal8QpmMZdhR8JThwy90E9k1m6TZSmmTK/R3OSLK7q0B09md5FwHR7MHZbqtQrT2BiTtdSJGesoNbR0ixlPojHloN+AvlVrqFD+FqnRz1prTTw2fCnzMvniBebQ7S+nubSqdFvUcgSYftLXDlWAOPlTdhxs6sQ/yW/9WEKl5PiF3VfkKL16GHhGRglcY6EsHoHDY9sml4trtkLPyiHBlx3OPriTNL/C7DT3dP29MUGhXv7jfy3Zg9U1BD0UbmqdBEe5aWu5kpZb0X45X1XKu7MhZwBIEYp0OH9UG9QQ9bkWXuWga+BtsVsMcyglTLmIXxQ4THjDSvh/zelKWlLmySaM5b+j0T7nBfavLLo20asX5zT1DNHuyyoUZQvrKz1OzwRV4Gyd6MRllPs6zC8SZOmC/mAXLa0vf9mJ,iv:OeYKLx4EuZBmn+YKXUVW7Yoa2iWguF5MIyqH5zqh50U=,tag:KKiym5zqsGPLuD5o2PGEhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-01T19:07:20Z"
    mac: ENC[AES256_GCM,data:u8MZP3K/2Ay0+4GMCDLh5erCbIwGx3plQvWem1QNo19yNL8ypG3qOG1uiWkjrafX2tdbO1COKD0FwUOxJn83X3tqZpWwIgMxzAPe3tSw/Ip1mKqGN9PqSjV0p4WrlvMJKBRQX/CTiC6Ygvaz/hcdEUyzmCwQC/Vg7fbuSFKZZ9o=,iv:Hswf0zg4Ju1VNrsf3mYkFvslIG2inEUTvM1YIdemqwU=,tag:lM/FRN9Vc6n+Yq+hG1YFmw==,type:str]
    pgp:
        - created_at: "2022-08-01T19:07:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzcaxmYmqviTARAAp7w07Xhb6NL8pLm6vp4MDtYelie+k9htKMFOMIw3bf/V
            nokIbOZe2jS1a68AKZgsgyQQCdP9aSjtRDVop4q+eRvT07Ircji0A5KgFgWbcnGW
            iZKug0RpWGXDxxIAfEBxYRPD99Xzh8Km8joR7IoXs+WHfVtTTyrB7mm4r2xp/sVz
            9elmIWUK07DmWszGsPbSFqCTaTUc2hb966aZr0kgcLSuZG8kRS4j5oBSlCmJ/ECE
            7hEx5sdKKaSdqfiwvWwexvmvQzzz3q3WVA2m3V/TvwhHc5djmQVp+xKiZRx/drDB
            2rm5Sz56XCn+D82cA0X71ExqDK7TVYzs56Q8EYtIeGDSvjdjYgIFLIslP0bdw4C3
            jE6riUYrN+r/r+It/0spulIqo8fltZEqhMZegcUS+MNna7S09rvXElSia5QSkdU6
            WDnS0hqxZM9l7Z6bbCF7XC7RuEBlQ2ORKwX/TZAguCAB1ofmNXzBEWZEfed9mfsj
            7mC9TjfqOc3l2/ekurcqImNJnuz9fvtldDk/ZTg3XOMhtmnykGgVPCdSpYYGNuNP
            gJfLkgfK9rJCyjRx8RGo2sPsPRZKoeD7db6COLauyDpaPOvwpTLTZKpWVzaRLvJR
            fXoldd9tPB7XMHmwJHSAoIJLE6CZSJLyKZObJZXppVaAmMpdB87Qp9NUj5VcJcTS
            XgGIvi4leKARj/w5mfJ58MgZswCQg8XZM7cChULA4arQ/13sdfIku3w7Ab6J4JMt
            86fuAVDdBJOlCQgkuY8lKbXMljizxddA8FMGdAjBQI+0gV+ROJM8nHorEQ+X6Rw=
            =IfnQ
            -----END PGP MESSAGE-----
          fp: 474383BB412F377B618401B0EC9439246857B9CA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
