apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    #ENC[AES256_GCM,data:QmaQFDQMhlkvcMaPPfcER2J64BaoanezRWUW2a1Ys0kkEDRWNmD8Wer9g0nFkXtx2NoXv4jGDKrdR7X+WlbMoS2G4VR+Pgg=,iv:Xboe+9MmFfxFppKeMskGEOQkrzEjqZEa1xsn3SCN0No=,tag:zrBs9+fxSWm55bU3MiYrQg==,type:comment]
    values.yaml: ENC[AES256_GCM,data:5g7by/o0ofaP6o6uVtecWgdlQ/bGvFoSQrL98+ucpKxl7CMnR/hukjj8sBLawyHL1UC8MgmA734+uE+GgI3dQ9zVoofVzWMzWxf6L3gu4cZLLBRCyQMhEfBWULlICaROBp41xnavPPTp4j2K3daLIJPHp/l/PdtybjdZUiJed10nBL+XaH+QvVsPZvQCs31BWU4WoM3OO5eL6+1s4wdoVeTrbISObpGc6vRLWuFk2v+11LeYLEPBKaPrHeAlhZd1Pos8zhiPFPaoy6fM3t8JJCN/WPkVCOPeqf/Bi+PSDuQsvAMvRx8h7Er9MeQNErX9WMPIEALpgk3IIHSAe2zPYRekuTxNL2TQjdYXS3QCGAl4bh8jfuI0PZs0E/lrN+Ig6pCLINpJSOiR0L0SNDR39Dp2YmTdX8GzBzrOrXvGk04ethdD0OmJeSbI7KwJkZqh3L97sD/p1GYotDDSv85ksOVtL8sKiCDYTlmeC7SVsHwnFvAhlgOHEdrPcrz+671xB7R8y2y/DpN0uz9RYVJazgi/,iv:I1dA6ztp2cT2hu8kafOEo5LAYvEDK7Q7z2Bjk1u7ztQ=,tag:a3HAjeHHg29+azzJxhZb/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-28T18:42:46Z"
    mac: ENC[AES256_GCM,data:oUlVoae3KHQW04aGFwhWFp0XI9RdBDs9e9+b+bRWrdONvBHHYeJEytIPoO6vsc3OtJh3cgzrpGkAJBvmFtQ7npFCA1qYLsSkonwrJyoeI5rSl24GSDpt/6b8ILIRzA2oidBrRoMdTyCvMcNp8SYmGprP6uajv1UC0o0LJV2LF38=,iv:Ui92J8NKFPa+XriAwfuIk53aLKAwwglotNdkHHvT6Bs=,tag:wRBv7Pnrh/orVuDxuFXWiQ==,type:str]
    pgp:
        - created_at: "2022-07-28T18:42:46Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxDE0LH+wAT/ARAAszD7aTmk/HJuD99v7hoBPP9flSJYSzjVfUosWVWXNx7k
            ARiKl3IyYL6VJZmkQ41QonNM60sjdSt+3DxDLaSFB+6wEQiMG1TOJD54gMybUIsx
            ZewgxBzaWphQamBXB5QBL31/DXsciYcQnshaIOendvbQwDgITPW3QUEbJ0oBXs8s
            fArV7qpJFXq/MR0qgJEyuIk8wHJ5ij4RTLL8FUKybDiSxmWUUTZzpck2NlpHQoWL
            EIw3S7AH/Yd4zpS2z5jf7q1y/9mQvMWBghoUZmYldSR3SOppbeMApFXYsqtXCpkP
            9cqKjpxZwzSlPUx1VeC4z7JWFOlGIBWkwUrPs5wqj2UOootaWXiHYblT/isN05pt
            mNk1kd5FKCXWiMOE57x+nP24oGDga2VPtOjxXdDfeaDov3eYB/w2vpLiZ8D0wz15
            vMrPTZocgdWuDYxAFA+9sUHG3zFuXR8BZJ+p/iG4Txb34L/fzmTt84Dwm/1/a6I4
            Qrzdao8KLMIcPK1Om5sZp6tZkInlRJEruv2+z94cAP23xcRqqQtxLRkqosJ0Gp9c
            yX5xTh5DZViw1MqV18Q8NFDyqpHEohn7Xk42ckExjfyFChAKQ8HOVCmsjSLf3/Nt
            fz8El5g1MyOh4ssDr/20TGps/lPdkK0bfLzCGxETaT2vDRudhIK3pHqCAZpYWXzS
            XgEgFSbapRDwwdZJ+7UucHlaXp9fPxsghtw0QnMmRI6xY0HRJekNSx+4m+fz8Q3+
            P8cTj9UcwBey0K2U5HyEu4UooBK5HziaQhNEd6ktO/rL2NwOXjLNla6WniaY8wc=
            =LhiN
            -----END PGP MESSAGE-----
          fp: 7FB001E77860BF60346DCD3B1E3F5A176D4B858C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
