apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    #ENC[AES256_GCM,data:XVHfFB/29kuP8faJt+Dey8k00nJt5AD/7Qin1ZwYk9SRVcxthZd9KxdjGsG248jYxkZyNA7c/WoDQToPMp9rUyCnRNGnIqM=,iv:WRk09fo3qMPsIPhcyWRS4ecldabSd0GKgQ4mpcnWlr8=,tag:uWz40PFeUkyt9Ve0vxXFHQ==,type:comment]
    values.yaml: ENC[AES256_GCM,data:pDHgS0BgTpK1HMoY/F+VLn6KHIBUY649niRji2S6QtM9hf02VPtgEnCydN261tuHAtnbiCN99WqIpj4ZS/5h16T5uFCakTLGpbMlVOt0NYoRxbO8L1L3YwoXQD2B6H03S9yLGe0MeRFJ6YkkWv5BkQFH/mFMzetx6NLHJd60IRrJfpgA73pRuON1WXqd3QJD0YON0GjUEuilt0ErNbs/hYQw2HsxEBqJvgWDMKLBPVgohMiBBRc5UtKyytkCWKcbsDsStXJCuoMpBhgCT0wf/KXyecLyrOYuZrGOK06A69Cx4pZWuf6/A5qDkuU8CwgyWy+w5r1QlIFsXcwaxhdSRDyKBzBmR0lU4Q7ZcZausJsc+d1d1AQKjAQhqPtEGxEaAXA+tVsnC2Libz0N8g3sjY5TDViPnu2BkHppYA9cOz8iuDIvr8dT+f44WbsIlOQrfXd2CYGEKOTM3YbHynvfvAH0q24ZCX0V+McT9SDec9Wt279/PRBZsv8j+iBZ24tl7kstc1kt2ZhTkPGwwL2tRl2y,iv:x80PbE3R0R2MLK8Cw/WuAVly0Tm2ziHHFTLnIX/K4Ic=,tag:GkQZp1OAHaXi887ap3Vf7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-28T19:57:19Z"
    mac: ENC[AES256_GCM,data:riX3dHDOz3ggQm7IYmuBi2xVrFisPGxsvozKv4G+OyMbBp23KbFxm4J5jMc52kbGetQ+YCUHlaQ/Rok3mp6K1JTx+DI3ICvRVwOIQ6oHLKqrKUBLpy7Ol7bjCPpyF3I78m/xVlSBI9C2068l4QI9meV0HHmxI2FzwzLOd8Zslbg=,iv:V9djJ2GHYfzowQUkstpQ1Fx3BlslnsM9mromvzdrNWY=,tag:mwvDBmREu1PUNcifyW44wg==,type:str]
    pgp:
        - created_at: "2022-07-28T19:57:18Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+nHohlS0C9eARAAtOEQkBm5uZ4o4NFslOsv97QpMi5fTOlHCaQvqQ44pm4d
            A8D5mjyE7pdlMa/WNgf8nfW9h3YwmZYR+UyhfGhCiYMbZLNoRzO0tdFjFW7sNkWN
            YVBsomqtomQ7MokV09sMaUUWOlvo8FdIqDOEdykemJSvgN18idhnpW9dEl0ZZ5vu
            hdBWeGo/6qtZbV3i2ayIEzqK/KvbMSChRCjIQNDSIFp9VbvVBjGkHTZ904vcOts8
            nKWYPpXfcgN+k5BLqJRKSAAG/UIu9H/0fC3L3qMcdYMII12I9359k//CFj8ziXEe
            Sq5lGBiKgQqDBIFOhpwBxze6MUCCQ45z8L39GNsWKwQAh8+RHPUPnyFW4/mA4jZ3
            Wnp1ecOWMo3/56WwSa2t53kSFPjMJm8AN4mZyBEFjcNyvIhE3JD/qQ5Urqj9KB9x
            fFfBGD1qKtrP1hzvy3IDi9J8tPGBQ3bekTVbCmfFIo3ZpxZT5UW2jN29X0ssCelu
            hnKjt0OkBRZsDhkMZUbVfzAo3EG3jBV6wqjb4a1EXa2odAw+FPtEb6Ud/GITpwQe
            iFJVWSYNixo2q6M2fmF471NMvuUSEke8TI6wK9YWjrSoV5pYYAe5WAQ+bwHl3Vh9
            pFhADVzHvC+4QLC2xVylNy7uce9vTHq6czV57MxBkHVOJ2tHZSbnb+ExCBLrkhDS
            XgHwSxL6KWXjT+kwPnGx9pk8SGJggXkDucelKaIc2qmWY3KgPQR8IhJur6m73jSU
            aRFOl4fzajvF7+WFwsGz6JpwzcT8QMtedfVdOKbmZfh6YPovzkk+6sxnbIIKDI8=
            =qlZa
            -----END PGP MESSAGE-----
          fp: E649F098DF1E282D10A23F2A59A6503499D30F50
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
