apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    #ENC[AES256_GCM,data:enrY26SfhH3PVsMbBMNIL8BHmvKyuzhRLIepd22iFxgPD2f6Bd9IY6IrYH0T1MgKAJL509OcAiDW5Bt7sC7g6JVDm4dQnH0=,iv:3H6BpAWfJoX75lFlwqCD4q2xegAUVrPNQMpiCDBSm1g=,tag:hMGaCayBp3aOeb+3wkH3tA==,type:comment]
    values.yaml: ENC[AES256_GCM,data:Il7h/SSfkkpc3wdVUOKO2HRY8mQLcWg8zYmh/5TYc6fndYMmW6HFgjsWWIU4GCy+NcEb8p+HnatDfcU8u/vFucxsnsn6VAjISYN0y7SMUjURZpmfPMOgQt/zQdaTp3jYugwFRxJhqg7KDb9ni+AUKDlvsabb7n6/ZRafWhLVbGhea0bc2CmscswO4DhuOrNOKhBt4GzdKcoqnyWfxGvDvV84jMJfDbNckfrfhXPtIXrQD+zT7lC2khh5DC4X6hkhhmc6vqGEvz6foARGF5SJeUFjrRINwAxf2W42NC25kTSPZ0jJrXHxeKwJ9XuC/EYCmDkP8kVHprVrCvOWPML650sopNQJX4lkewXIfrsSxRCoGEjBxnMQifsWU1Xo7EhhloefzUz53lvDG39Jr+ufWoCa6U+tQI7Ob3KH0MrrviP/ky5ORAzVYDkwma0Q3IsKqOWvy7Ct7J+VEdz55VunM1dlBpkAs5vDSbqyjdg1d1zQw1dGAvzhjHqcntxILWPZ1nmqr3K5XBzo1TnX3lSSpA+2,iv:tZNBvzX9WXlbdmgj3DbYwm+SX7fBRCjQpySKNsIWk0U=,tag:nrYs/UYFzB5hsF9josD4Ww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-01T13:04:55Z"
    mac: ENC[AES256_GCM,data:2AaquD+5ZeTPYXD1+6JBaPQLA2Xc9bJxO1QMy4T/yNCELdhxUMnCgICTuJXrNuBFlRxi9RrLYBa1eL/8L2K4NQ1VXtgW9XWE+8HNNA5L3ic2UxOMsdPj2PX5l82j+If8bkm7iT+Rh0lJMFp1qupaCGsKlfNeXhVTdutsr0iE2CU=,iv:UXGy28pqOTTbvTRDNEJfkHYv8PUX3Z4+x4NUnmrwVww=,tag:+1xxFX+j6zI8nc4BaHZEBQ==,type:str]
    pgp:
        - created_at: "2022-08-01T13:04:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxI5IBHkW9jaAQ//fA654r6rIvzt0Oh6pJ54AJhd3dRICa9ALQictf5PCNxm
            TCCGavt4yf/eAA26ytEKai4toIu36KhsKDsZPjgLXfDJX+80HnpIMQMwBH9oMPG+
            WJlIEnpbl704Eg2trTW+a/L05yNP7O4UPZ0S6IoxpD+okrOP/p49ndNXYvrwt/mx
            y2fMby+64onbIFy4KJIKAhIT0UswZdDqrxsMCPr77JPo2GgJiumxxlcdrAAEvSJJ
            a9sF82u1Puksep0UBmJ3oMT9MFgfk20dRbn9tQ/sCcv7+n7G5zgZLsBg+wKFgenB
            FukGzKc1+NOAj5ADcO+r0HwsdQuGQuUT/UOjewFRKTMnu8eg/Rb0vJaf47E+mN5o
            raBJzHNpEashQRzQoUVZuIrZCMJCGUnkQnEqra6Vq4GJ6YIe194jtbeYeBnfKw4+
            nQJlokBKl4k7an5I4HqVXagz1naXjwfQ5J0JNiMM23lHBc5bWfvj+eJ1iIt2e8Ze
            lXxe7HBGBsIl5NiPzTKjj2tdP5xddjmR+AQIJW7ulyazOOSH5+5lMnkTUCOLeqxE
            3bon0Z9riFgbEHrogn8j0vavLt/aAb2zFeiLa05EFwwGDf0z0qW4izGFmUKG3jQf
            QuUAtXtqkc5bJve8H/M4Cpzd+pJPg3osu/gLAcdfJMCboD+QOBsMKjGu4QWg/+PS
            XgEetQcC5ONjF0j1iAUhg1ujoEk58ZtKscP4TjF8zZtK4qiTYOrxHeXwB5jTiwcU
            El81yM5UMtXhLiRsmfv+pRKShLP/OMel11Np5ai8or6TkhCNSYWHt38siCor4uc=
            =gf//
            -----END PGP MESSAGE-----
          fp: 1CE2A3387F380CFF251A805B5CD907CA9342EE46
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
