apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    #ENC[AES256_GCM,data:p5KWw372nTPGrkk9oMbess/rfHH81JsTMemfWnVXhAujvx+p8BAiNWAiq/xwLQ3/0AbctUU/2KtzlzHKsLjW0jTryIhZbFg=,iv:eOPnUjBn9ta7W6D55cAnsb9O6aQqGWGMy7tlFRqobXY=,tag:tqYUNzOSqx/206TL4BIMpw==,type:comment]
    values.yaml: ENC[AES256_GCM,data:Sb9vJ442Kum5SR3Zm6Sb829hQ0R1ytpN84QaBqyUJWzsBNfW1hayq/nozhObh3SnWuQq/hvZchBG79MnNJe9ANTxIf0QSaQA7a+4Z7VKK4FBSyBsWzcD19J0WW6Lh3DeBP/WRQLX6tLRe5rJEjyeNhYuDEUL0B0yzYmgYLdkrby8jxHgXfFuJJzVc+KScZ/wKn6fX4i7IwafagFumow08FJnTbMt+74iuiyZynt8/+CiJIXa6lU7vFK2NaI4I48eq+1a8zk83WZcZRlb3DBWIyOuKFhSWI+QM6Ayfqwf3XAAsqFvvQYosoobfOCt1ryc7XbQeNh8nQ0/LNQYR0hzu+o8kisE81oArd+uKC6hW2up+fB4rZHL0Lf+rXaGEGhS2Grt3ppo+wjhepaf2AtZFqoDFdTtHapmEqXMgqftho2qCBMs/1SxRK/lLjezEI407FdMAP8ZuAeIaduw4SiZ3TOEikWtEqpi51FO6yejeGVerMqlKcnICxD3UMhHzYKLjFAcjb+NyQVcI6E2sd7/V5gv,iv:YwVgCX7FesSNsB9dnz36tXVd02CzsZxcfKITFz44F/4=,tag:tdQk2oUqwNJJi6RotL1Vrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-16T21:45:40Z"
    mac: ENC[AES256_GCM,data:vQURbf1LYqZuAt5SSiV6GbkE8Woy37s2aB736KPXx74ndzRJs897wiDvepoD6Hwi1SsMpWKLrLIGFqZCbn0Po6xPwWhaIa3RYKYwMFLpqhx+9qQNMhzN4FctT7JtqSyxVOH+W9eqSa0pqzv/gi5GfXuXDsnsgel3fxoRcbnv9ds=,iv:Dbd4U2CnHcs08eeNUrPsuJFEdxn65dnYnxFHPPV3z74=,tag:3TyuJ7g6Iq7OeBdHa4jn6g==,type:str]
    pgp:
        - created_at: "2022-07-16T21:45:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7ubzatorK3AAQ//bxjBi5F36IUoOvQVaw7fyI89OPiJ2bFmy2DEP0eW5Gei
            yNsjqQV8Fk4vXJdkaFvlIowE0xREEFW9US3foTowA1RFVcDl8voPCbYHVcpE1byq
            t3BozXSwqi3h4MCvhkTH3HZUX+c0jL/3Mm/nZs75avFaOoF9xFIWH8WWxkvoVBPf
            NNmgsGMU+/OcIPVx15Qx45jqlazsWp4b/F26Dq4ZvXNXry7Tv8FsH5tSAjNh5k45
            K6bUtapa25ip+rMs61do8R5bD6w2L2QCusFQ/onuPqu4nPnbjSUsHBDCi6VHgihP
            Ogc4eSa5mAuAxjr082pI/lXWO0gmLlhyNSY31VQwWlpN26Uud/kLtoJZ8pn7CpRs
            LrmMgB/PtF1DclOoZR1MCGCd53PJ8SF0DeFaxCVP9aX4A+j1jZLs450qC5THHJwq
            PYTbaXPiG9GEmQAUlLOeSWZS86digWeRjgMSjCi7DgGdQ1Az0JaxBOb83TvoeKCY
            ZqulqHCiTTk7GBlCFecXLpkHbd0J9UkpbcLeF9x7LlGqRY3S30YSZGvmHTADJGbW
            zOdSX24BtwfbUqb0Vf6i4LSCeiSjeEBNtmUCIuV+x6/g4yg1ALLfr6NgG2Meahfs
            SOUnUhkuWg2sadN2maOFc3R6DLfafLqSKlXjSZYtCOHPTLVJDFKxaQFlceo5NcbS
            XgEtuhzrr38lY2buPfcXcu5kSRaPXk968cGOQXXA4/buNvdN1c7Mu6Y30f+NAUhM
            FtgzFJDvOHp/Hew/16zHAk5nnlERNB6GT05sd8+k7LIjSSfFOZ5XqVzfd71zAeM=
            =R//l
            -----END PGP MESSAGE-----
          fp: 1620919B74CFFA84295667378733247F28AFE256
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
