apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    #ENC[AES256_GCM,data:QIe2zsXRHs1L1M4kRsu2NwvXcduhfL2h1ey4uZL3yHyXUjrjU5O7p3VDLNNl7l74/jTAMPk1Sa6h5bJC1KOTHIC3/ZD/4KI=,iv:WZjo++V4h35VCjE5SmeQ4WlsGq4UN/ULw9jpVBVOCU8=,tag:XhVy7lMRW1+0lvV8l4EeAw==,type:comment]
    values.yaml: ENC[AES256_GCM,data:ZhOiy+hb9ZYxuQlPzjwFndyaCPRBKaW2/ViYTj/Sj3iJ+k6+IR8qjCjw1vWbQDGE81ZiIFm3SRLeiVIwidID6bueFTGsj9WnlsOEx7GmIZdMG5nGObs4BgUajEa7TA5lWNKZRZPF8qFF3SnnIKxNqwAmLWArfS5AI657pNYFXOn2718b1OjqR6z+i6aIkszJ3+BAuxh8/my//9th5o67L2dFQd3hvjl7imsX8pe19oaEOeX/u3FDejLhKA0WtKgloevm5ygIslqnxBYFJ9kckOkY6Ld/f9lYysYObkPWXVoOiLrVVe9M01YeTG4PYsCA7dODfycop+NYBfURsnImkmhrwu52DS0ZCXLI8NnExfOV9oAg+fg0cbI9/djDvIWZNO9l315IZbKsmj8mR75/ACcLCMYJcdLa0u+/xq+ptxGBhqv4i/jQIcZN8mrxpw8TkLwDpbnMs7vIqFyhw1ZfCRW5QszTcg6o6LEKmkDa6lYwhsvDDVS+IlW7rEx6aZf2JMWmfjHXLgV/RGTfh+SctdfV,iv:IEecRAdapc6H6LWjGwdEDqsCiHpCqNQalLFh6UjNhCI=,tag:rvAOqhpfVA4bZQ/e/M3l+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-02T02:18:11Z"
    mac: ENC[AES256_GCM,data:7zXuZhNrM9gWMCNw8aLrtoitMHHFF960BzpLNU+tkp50aTeyLm1rJKxTt0+h8m7NQ/bCgzaKTO69XHx3xx092bC5wHJ4dsr4GTi9TJooHF6gibhnHJXfGkgEyFWfnggFFttOz4xCZkgmpauH0qCt62Tmm6L5ZAAluVhB1GU9YS0=,iv:8lHZ48nbV4lptIgZDcFxszKsAuQSWmVZtnxovQZScYg=,tag:g/JOWnBfieefU+JWa5x53Q==,type:str]
    pgp:
        - created_at: "2022-08-02T02:18:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/jAMpB8FGVzAQ//cVlpZv40Y6yExSccg6EzcMVUrNvJoo2wdRwZuDpZX35S
            PtH97K+KY9xaaSUL2JfWuLC81/UuAFA0L4lCo5AmmXJSrEXMZp2f399mryLXJ75u
            5A1aRTENaRl6wkrnFVdXlszvMw6d+hMh+jQyYyLF1aDtDWrCHPKLeWFJcE4rXRDr
            Lu0De4ZlIJG+Abay4qwLN+lKjpSLqQ2YBzasJOloRUrvk8UuCoVbB+Bvav2AtoWX
            4+SeuhULdQabEXIADGTKViGbyOGEWjGMHeldfSjEzIpVV1yDFXn6kVHxHhOj9nPA
            2QquPvsC2M32OZPYCHz0x77vvV67ZgD6HheSF91i0HnzaLK+kGhAc5sq0/vSAW+b
            bSO3xC70rb6o1GQyjYSMBCzBpov678smMopr8+oyHFR5yEMqP1Gm9FoESVgY4bUQ
            DFvGC6RsZSOhi7Da6oEYa84MNPVOoejcGBK5WZ4zpjdPmaXyjMg7mcgH7W1Z98r7
            0ypSlmseLI1RhRsMnDuLs5aDZ6YZCbZEXS3BiwaXz4JOzxLYQNSqiGHyo8Agyc4m
            kcQjkSaC0UHGC+YpMfqTbfy/ExQUrbnGNpKuddP/5m6Z+zR3BzI2VgCzfA9K7PBv
            vKGKGe0XwotxragiwZtpZDms/GFsz6jm/bydSa7Ko5p+nm7tWccChdHzF7Nbbt3S
            XAHGCP2WTmdkRyNrkYNfHiIOnWKpNX4v45FghK9ZB5VxKIscFkTFKVLFcMp+iAK3
            GLb5WtOh0bg+u/H7KLpK3MtjMhrPN7O8Bg5Y7PVD2hIpkhitFMbRzE5C3fRj
            =KmxM
            -----END PGP MESSAGE-----
          fp: 886B5156B156C44BD19F1F611D38DCEE0007E84C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
