apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    #ENC[AES256_GCM,data:JRCu/3M9v6Iafx7TZ+KC5R/H4xO2KVDXVmJ3WuNf0GxoeS2ZXPLK+VvxsrEOthJhHwsgjpR96K8j/xxpJb4xbpaS6ygCm2M=,iv:tgPF0QOAhqI2lFTNnoYCJQ9qgRdcSvBbHzA8R1jns8U=,tag:sz7egAnGdWvhHs69EwF9UQ==,type:comment]
    values.yaml: ENC[AES256_GCM,data:vVEFvs9Pr2slxlfBiV5/YonXrAZ+ZG+pLcYR9qkjx7Fs24Ncq4md5HnbXw9nSdWLbHvFI7ddoDiues30c1uGAz0lLcp0sQlTSgAw0fLP+P6TYg5gAAacN282nlyleWVoFoVZFze1+Syi9/KlaNZf96QaTbWX3bGZp4j1va+4+deMRL2JbNu7GJ96f+BzMi5lwwzM89iw2UbxpEEVyF4UutxqN7W93MShUFgkEyPcsd6J7nAMim/KSG12EysKLADJMiaxkUHhS9qS7ZU+WEXdYTOUpisWbVEmrmsSwrNt+jYLCJeioIRP4fc5XxDBDAvoG0bblSdcOQJ1kSnq6ikrwggMFfEDEMjomxCcde1cTXK/HhnWaKgJOvkdRNx1d5NXHA5qz/pPabLK85Barvf0bwGk8heENa2eCkDyqYzOcgIyKj42p/nSunktSzKKnGLuq7lfwzo1aDqqWatRgVw5mrZsKj4d6rG9BHJMsi98+GsAJE6xPn0IGPU+FQ==,iv:GRcVSFHx5GXPxcBYFgqmTbTTDkIU1giToPf3BJCb8mo=,tag:FXQ6WC5VhNqjxmqg5Ll6SA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-10-31T20:02:11Z"
    mac: ENC[AES256_GCM,data:ch3Zz0Mbk6gVygPdHnHbu9khVF9Ngl6CXZpCLLIAQ3X4jzUkA/FE9gFOwFNE0Avu9N6tjYSdVFEH9ESqw2k+lk4uVzqrsH8+J1+6tPe4MUlgktp68cVI555vXrj8f1+A4eW/St4l1TCPdUhSgYKBhE/wV7rDwoKZ8AvkYQRXh7A=,iv:8Lh+jHb3JasO/gaGtjScAGPJ54rtrnEtHZ9kAWySbj4=,tag:gLvQCxFRtGc1vaIMKsFPFg==,type:str]
    pgp:
        - created_at: "2022-10-31T20:02:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/y2e1YES7nOAQ//bcde0Wad830EOrLUQDA0gcQU9ABY6h9p2VEAP58hNrpS
            2bjpqNoSp4kOu97cM4+rTICWMmcO1A6U4Ta8PYx3L7I8+2uLArqSO607THAcPUs8
            /mi1TNmgCMubyAdpo16szHuR7WB67rto8HOPH1Tbw6gSbdYcocO4WmcX2ObFgaNS
            Nw+S4oLlECZrlBHmToDYmOh70QiCh6Lb9xng3lyZEj2KkxY562AKYsx4ObVG8FEz
            K877qWwv2rkXGbFPeB4czpCUSG7hJOPKwPImtn4arT8X5GaYlwYUyD4pmxbRshLs
            qs2LBpqZUddPl9NNscMT9T1tP1pVxZJS9LGUdWoaZskH7iQOtlhVAtZZW7IbTbkR
            y5IbODwqtCszpscNLb5Gg08IQBOQzWXl/2JCTjRszxrVmaM+bs7Ym/akJoVI34KG
            C7FcQmP9fekJ2NqiW+kOpLdTL1JjRmhdWTob0uO2s1Hd9fE3O9rKyG3pmn6fNmpO
            ev6aum7eZ/30bTs/zNdxqYh4JRqfJ6ZrcoMqW6VnaMknWWutcCEbjfTK5Mi9811B
            rg/6THeIovlh3mn2UickdgcLyVJjJbwU237VtmgzTVSxGpjoXya7MPYl/c4yyqYG
            ajFDDVFrntG1uL5IWW2gP9ePn4evGrw7aBGVPqMGeB1kudQBuGShkykOzidRfu3S
            XgHdrzbe4a4YjBdxSRDD68Xw0k6jMObQdC34oq+YKqmxirGTP4dVLgnqYM4w7PKQ
            Oy+SnZyuv4coQ+I1orjY1fw8iZPVheIxDBcEzDGcnvnhKwl/h4rXTE2okY7vviU=
            =5seS
            -----END PGP MESSAGE-----
          fp: B67DC3E37B9EA55195AC0E090550497FD25582B2
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
