apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    #ENC[AES256_GCM,data:VtRpGHwK9BU0u2rHHwEuD2jxuLwMD0Q+hFExpzYiKN8ZrCQXy93wXXuVBtR7cVkfjaE31gtG0hPC8MnJ0l3AiXUtACCy4DA=,iv:8/YfZOyqs0AlZhuadxR74ZUde6oED2WmnR1oj9lNVdI=,tag:oZgep6q14yCMdiORrNqKiw==,type:comment]
    values.yaml: ENC[AES256_GCM,data:G9D4Uk1k3PTqHVdtsgKdYkkJhF4R2CceqrYmk+GNI3EmT1sJ8CMPJvvls2/xfSUxnvt61RyZS4kKdcJFVD3Wsd9sR9fH4eaaQI6aw0d74+qlSeGp0W02ecikz/kgtkKrMoiKl+GOueu2EGsea4PB2pKeP2CL6yvuj9DPZLiVfF1ekcLdv6XKj5n91s5bfPsWpOFdgYNlUHUhnCCFwMEjckuSMaYl4uywfs+KHiHGDw6Ec1PlfZq6t4MyT6AUSo6MUeAw5Qrop0S/IMvoEmbW3CTti8+JfUfgzWh0d8dxY2wXcmtTqpNrRmWeiFAYFcIiSrGl7JNaM/mb8Lf/uMqpCIjzUL+LeTxlnNJRhDxzE7IXBt5ezisGewRBOf0SfYprYtlbOM7s5FxYHUvMnrw4s/zkvYDdroxusUKHlYdB0+YuaoxLLedM54rxzC8uBWiOhMbH+jJQWMbMIyFw7V9Iwlbnv0oEWGP4cjYgQrKfh5Xx2Ep4FgVsXn93MRjopGtewrkndZ3o0PpH9c+9Eri94NJw,iv:Uk8cGmIhFVZ1kuDQLtwtQkNbqNcCznY+OqPcxSgzctA=,tag:EGyp6DRf7eFYyMRqBKXQVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-17T04:10:04Z"
    mac: ENC[AES256_GCM,data:bBUsztr3oKPwoIFxfAcPfpSUaQgwxU2jj6Dqj9G+7xIUwrKlEiHg+M7XUAxuJeHDz9wsyW/vZGnY9MzChLBFDTQsyOt0nAki7BcDq/VKdfqGoqpoiEh51ObfiVnzKgOkCKqk37QPJmpUun04oudgFMytuE1QUnZ/+IR8LhTAFLI=,iv:IySzFpqXy6JgfIwr9hl5W0o2cH40rObbzu5vg/PFXqU=,tag:vFrNlVsGxFL0vI8Q7cGPWg==,type:str]
    pgp:
        - created_at: "2022-07-17T04:10:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7n6Lu6uEOtPARAAxXkcaZeInCwzl1HhYIMZTEPOd0NooXWRpAEuOCz8ovHJ
            Vlfd0pxp3vd2RHWtsEEH7no4IjVhfqoCHuw5NjRbthAcWAEd1Xm+SD3JpntgSuvI
            nFle2TRW/1oYmlLqlMXCF+HQlajMLVyq7ksptAQU8mLAu+RtAa93o834+zVoq+lS
            eIHwJ6Ja/PlwWNvlL8PSFD3NXEVAFM/y4juAqYkOKYO5+yJ7NadNoBEzz5k9N/G0
            hLf3ow6TEq98QxixHtuFBjLoNGdmls52BTYiAceM35wLFRK1KNLtRIVX8r9+H+0y
            3502mJ44S3r4OkJwu3tdXqgd6X7qFyO0C18DNff+TrSbStiM++JtUMk6vQor8Q7M
            1C6MPkN1cMRj56CDFFa7I8XrQkOtVwHQe6EQjjXClSgIuo8wNxbqe5yn6LwlJnYh
            jsanc5EcBLWSUqfAdoZh6Ocy5o7J7sPuS9eyqC5FJA4sZV/Lkq2bLnW2BDU5NGfj
            l7PST2xJa6faGLtgwwhdoQqFEgGcwdWIroFVV25U4/zbQX6OCAfjYU0sKGi0gqfx
            SKP0Euvhb2Slif99G6j5+NeCE+fdZsBMu43Gy94U0a4yh++L3+T/UbU4LJybg2Q5
            QKOhmJj2a3wz/8QVXc+2pMtQoIfTrOVwhiY/UC6P6i7EdUHkZfSeJvC72T24Q9nS
            XgEKB5wIrkfbU4LJrfDiQyHWi8JJjoF/91fB4ZGXgCGX8ZIYwaZ94CuAauXAhr9+
            sBlCIxj3duJVVi0WPExdexZ/+i8NZuO9uyKPTVoUY4iBVUCldbKT/ZvoCJxci5E=
            =nLk3
            -----END PGP MESSAGE-----
          fp: DC59619C3473D8E49ADE76B748450F69CCB7065F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
