apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    #ENC[AES256_GCM,data:4bNWXl8XAsy1RiMas1w+aXJxR11qYhS8H/zJSYTSHnW3T8YkxxvV/j6gYA7jlX9XnoC1Oo+tqyutnj3sfa/026ssQJLAC3w=,iv:NMe8LeMGd6WHLkrGiiyPeLBhEaPOdwNmocfkZz1dzpg=,tag:EPTRXjI65rc5/fOjU4jJGA==,type:comment]
    values.yaml: ENC[AES256_GCM,data:EIB0agKdwb5pDbaYZNb1HBkWfSpSiz+jvmWLnYVjQVyFYtbK192eNtf6J8IN3kT77jD4FUgNTCTPL412aQhtgeZtPHdw2jPLEJnZx5LW7dbK+7t3whj+Kxmy8HHnPg27IG81dQiLl3qcxcjJaBmwI8n0Ul7b4m8eTApH9uTfeo6sRa5b4BD0fAHXRPaVPgEvkSJ0f3/3K9kDKcKS4InlmReQDNEvNjBpfMWAonQcs/AttkWfEwNSjGZhZsOSFdQf5hVmtVmAk7a+PaZUKdU0s+77J3D6X3Xplo+g48cemNQwHow5Yym2YO19Rem3AttVIQtmRcArVjs/aUJNr0RE7AX4rfyUiqOpO423qRFCxYduuYQK82madHJ4mtG8OFUbEuhzPGhBqrObXZvUS58ffSOzNIX5WzvINDxRhmm+4NN1Gprmnmum/sI4X/mAFCa8hxrJ1S1I2eRCK4EHBaksdlgPVQpdNEFotFsGGVrI/fxUfbgEsPKlPTNolmAjnoD0QPbF4qqGGmzrLRXVWDumalaj,iv:5PNWX9ft1nu8239SR6/B17V8DhffmBS7LW/a3GUADis=,tag:N097af79upeRGCNWwdSvKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-21T03:33:01Z"
    mac: ENC[AES256_GCM,data:mW1HkSD3xAiyG8OhJu0oYXqe1UqrOF6UvhHSg2H4j9bum7zZEupKylKwI22uvFnPALJi85UcipRORs3mM152OzgqkJbqp/zLnkpcdLXni5gYaLrcgiQveaUI1QAJdwEB63SyxmkjgH12RKQKyKQysIeCzuzIgv1UEHyR+XTIP58=,iv:41C9ak91oXYb4zzWZHhagCtPG4tzFeEOe7sz4vL+Cas=,tag:ZRKxNepdWE8EzF+0VdR1sA==,type:str]
    pgp:
        - created_at: "2022-06-21T03:33:00Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/jCAU6ThN3FARAAlenzki6iMpwRj4giqGL3CCKyme0FUniJqE8+2rLAnfVM
            kncF7nGhgzJVaEOwndsux+11TRZk6YrGLEWSIFPGfHxWj7/44Igg010xYmtbtghf
            ZS8bM25SI41UDAAvZIYb1RqbeyVNteTyMwxXwvomoVWhoUWJPya+uaVpbe19NzBO
            Lvm0gAOHkLlXDZqgmfh8Qy59TWYKw+rxdZrMzOQ0X/SfXXDqRCUxeWGiWJQdK6Pq
            ZGtv1TeT/T4dp4NiDQ1pSW/SRzityrvo9AXT//Coy0U9ZKWxl3CqeuOEFIelJFFB
            Ri/eZbr7E6AoiXWpQlQ4ol6D/4/sbK0+cJFG6T9IMkzqkIEzHtotGmqftF+pV0J5
            FuLIhiuKNzKw3cRv33gLFsQenZhDFqxQbbBHRZAZXG/LyLavwFwJsyc3BDvFpEX6
            8p9vt0JOTbXRnE8wanDUJO304aQVrD8KXCR+zwy2l2xrBELdp2/8F7MHw3HjJmDS
            U5xSD28VH0w7b9CHex89YN51OmU8kz/6/i3Fwu2PicPp1vUc0MvqrNayTo33K6yA
            oD5Cyp4BDdYZRE8DhxFNi31Wx7n23Ieko6BUL9jc8l82BJiE/XmYhRK7vDu3P8Gz
            RuCtc0SNOCek/f9JJErh2U3WxbUc29/rutrDAitYL5C2XUCprgcPAQD6Ne9hMcHS
            XgFWqAyauYBLK3asGlte1Cxy6XJIZtjTYAZr+q77KJTQvJjvwkNhwm+vpZ/cgAkX
            sI3NqBR6eEHP5xVHbNVQDxatXaxazfoHhPd1s56TAhbAVUQRmfPLZ+OUUs4RG/g=
            =ZYN/
            -----END PGP MESSAGE-----
          fp: 02523C633D5B3DA637275885DDBF00F747D23864
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
