apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    #ENC[AES256_GCM,data:w+W2HoXZoNei3IDVpASdmFGP+pSUFzp8WxtM9bwyZC8wKWEUZl7sXC5dyuodbNpNUvR5e6GyNNAdEmSTjqyR/mvqI4hDdws=,iv:qbmGlUGFiBJuV+3X/cm/BeneNqgoGTcFu+ELbp20CJM=,tag:FFKmF0OgGEJLC5q+yrQBnA==,type:comment]
    values.yaml: ENC[AES256_GCM,data:Q2I/LPkKXM3TIhU2OR9zvWT0s7nsnn48alZRbJm043FEmwzd3TQluB48EXU+1q+TumV8AA4rIu/unu0h11EXn6XXcb8NXQeWGnRKQ7XPnubRShKMmHBpqSSmONVL26Xpg38SUm0V+dK5TpQu1rURd8oh/bYOfi8TyuAFkmQZdB69hcK04jwwBcfhmp7bAkpqvOvOP9MiZ3NZTE9GDeQNHuBKIym4JEJ69svdlnY7Dl+3F8xdoNx1/CTTJvCIbXD0snXtEGmAuhB469utnIJsabZengqQ1ISU6KGzg/JIB0KX0wQEkNrws8xEe1UFXNrcbho8XfP2C6X/2H793ASn8ybkD5Cx/YHImPg6out7Gk4xBFHAld8XB/knb+0tfTWpNrPNh2cQZG9sR6ql4RZgzUfOnNcJFyTMmAn79DbFoi9X903qZdWkhbzDU91muX9cOhac0BfirWZ4fEzgld5gQx2DK8YWv0nkXsbWMXf7bpPoL7ZzmlfRCke3LKmtdaVcppqctsRwKYz+kvigFxce1DLh,iv:HMrYtMte9niSeTqLFNk3YVYzx8FE6UqhxIXwPXoGb/U=,tag:1vMOKi9psdChBKjPuHDDOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-17T02:04:36Z"
    mac: ENC[AES256_GCM,data:3L86uqUX2RjOGkLBJzYvTUnfOqRtoSROU6zZW+7moVCX7QXjOgmyMoi7i8VtgBq+VkBn0zuIITsjeZcyo5vT/yrrkqE7ls7JJ8MvgHSd2QRhZUjqC/G+3l8Y8IshotSMoq4jpVUVc89YqezyK53odo7xZyN0Z7/1ph9gBSDrXqs=,iv:uzREVJEe3JEcn4GmxW7kiSWIURvYoZb5STlioLYru1U=,tag:ThqMSIYK72Qr3jT3QgwCqg==,type:str]
    pgp:
        - created_at: "2022-07-17T02:04:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA43ScdNbMjLaAQ/9FL7AxEy9xEByRP53UaFD2CHDsLIL687KTrra649TnfLp
            VQgulgR9OGArKs8uNTcVmDms2Bfi8WY9bdf7cWkjqpM0ph+Vpabp+d/CRRvUDNjf
            sOvVozRCiOi0BZrtmIt9/nmO9tYxYxtHOaOJt6SihCPpNgy121T+Hnf2STgydeAW
            GAFjGu1lfRkEwLNoSffXqoCzWfRP34TntokAPzWZz2wr4ihjTD/SwMbbrF8B6/CR
            v3pz4rT977q2dZaSJ/CmoiEze7rPKetw9cXlMCn3xwJEcIGhLxIie5822jt0mzKP
            vqpk7di6R8g3lki+VA1+Ll1KrSH/MWFGkIJpUO/gC3YhaTgmXjaOpJNFhpw9Pen+
            zkwDxcLIY8luoCU951GLy0czDo1G0SfrEa1zdwrTw8AuSJD1ufMeeWA3Rbeip4Je
            Iinh8+MTJ2YcrFss9ZW7m/gXikwyuFvyZErXmKcvHeNHj2zlFTDk9Me0tjprrn9m
            KPUhSASWnkhwivOOrGyscjE6E3w7PrfVcVMvyjAl6xf9PkIn3Oiqs1NcnATKLGQx
            M3jE0J6grG5GAGZULWPlT/WnnEiM5kYHFWyQre79Ic3tSzjM09Yv344ZhcNLiAQx
            wFYfGcLl+ZDjyt+d5GP6687g9ccv/13Wv+oBNxiYTHbS5g79P/U+Ab/LBpxo14fS
            XgHDJpJAf2jC7VqV2FVEFqhi6tejFa6lkGmyisV97sgsX4gRU6ZKJ9lfpks6riMy
            EkNb5NLWMTNERON48GNKVzcOKlNIUWn/A6+4ylk0pMtShhsHswRb3Dkctd+n+1k=
            =LXrO
            -----END PGP MESSAGE-----
          fp: D6D0B43671D8EE79240663BC4A62CAA5DE46D9CC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
