apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    #ENC[AES256_GCM,data:CmE4jrB1rUPuvCQF2BcUeWPDd9Xep+Ejr34GQ4LSOI8pA9JAHt6C/CQ4Ay64ujyG7LqupMPQ1kaBPNfouvZ2Hu6knf/o1Y0=,iv:LwgrH2PuWxiqspvCC6NvFfQqgtPak5Z0dbGoK9eG6a8=,tag:xkzxYEY2tj3WK5uD0nWf1g==,type:comment]
    values.yaml: ENC[AES256_GCM,data:3LVqHqWRDAjuKpC50FXnT5iKcVuoURPzqD5HkWt4CQc01LBER2knta2sMp6UoLzdGmV0gx8YWmhVP/V8LOB6B8nOsh+Z2jdynQxKAFX5otoOf4CGzj7mrIPK/cjWZyiISWPhSApsSaDNswKExhEsNBKM8GziFcC0pHpzfcH7weCI1M4Co48A+pz6V4x0cIdBxfLd/Ik30AA+kFXq0wLGB1OTlVM6qlBZ1iE6FPFTS/9//v3N8rqFnHry90P/AKpBBX4uBasRcpLn5AJCJTHkli9spKjVHtKj1pUfGxv+yABmoXFccmfae7oy+w6jMPrJ+/kk/rZKSVkk4++tHCvwRrM2Sn91lu8FYYiTCfxgtHRjXtdj723bS46v/7hcR40vG/gGJd6rnsAq8FtQkmskITf8GbfjYt6o6rd4gqWKn6blLias9vJTRVGlNK4yDV2jyF1qUAlrfXoX1C2eAldJyr+aaCXqQkh/h6VEH4eeZoLyHmf9QEEB7Y42JA==,iv:V3Mseen/ekSNwnML688fayfunMQ1qHdb/W3GNpsqmkM=,tag:9403zdWX7CxHxB32oLyn2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-02T02:18:00Z"
    mac: ENC[AES256_GCM,data:ofcw3Hv5GiGi3y5lnMO5iR2YT+vO5Bhr2+XgSqWq22gbIArmwQAMaj5vSK0o9ELUb7jFJh9GXwBfj9aMrlfyF9pbC7VF0YgU6+h1cMZZEl3pU2Sk/4pMVf5WdtbThHtSDqzLeJKFkUSnjkTHwfqbGZ4dMh3sqC5a6S3FpkBwdNY=,iv:1ejNV34Bt9y4wq+nZEe37jpj2YMHzObko2hx6taj/tI=,tag:jxwaoF9ze7V2uETubdJkVw==,type:str]
    pgp:
        - created_at: "2022-08-02T02:17:59Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA791CIFrLnnVAQ//b5kqr0kjhJB/UMJHPsC0NPNOy+olR8FvgpmVGbfgfg1l
            /gXP5Bpu0EZs+skQGQAFnHe5qAAf2HN7WrMRkpi/07hq5tJlZhUPwDLgf813bfPV
            qfpJxKK/SBiNK91gu2j5xR7M2ihFMJud5R1bWUpTTAVd1Wbxpmtj1PavMGIhUrEF
            zf/PS7ynRUzGFTXzeq0yPJb3FZ/dJWs6++2UwjUdiNvbFoUGFVboB5R56VOtNmYU
            stSbw8pDfiVBaK0uzhwc6nM0ZB8Tf9cS18oyeSUqmTLYNQnQp1FbqjEdK47DEaNU
            asmeiG2fecoshBMksMd2fbcgniORHHsUZOCrLGQGpqOgnODwClFvGJsdPfPqK9aK
            i0gulERmgZQRUwiz17WOB4VPVVJoH5NV4CUcdWDDIPlH0tgAlv67UDxajiOn77y/
            SNI4QDiWQInwNgZLjn70x+LqsXYWskgrqe7sf2aphZ+ZYBaOwm8SRxy0GlKMsQ5Y
            Wr9POj8sD0Ak2JIf9z94zOKrRNf8IA6iCVkviQ12Ipmbl04jzrJa/uAUgs3oR0L+
            iCb/Wu+pdLGctmqeo3QvBZOH+39fw3WHuIfZ6Q1tkqAsI0MrO+OyEbI94QEbq2G5
            InhXvLzzU/t9SyzG+Qn8nQFSrKqgSvnU1GPI/HHkxLzCtDjCCNTYyrve60t/cW3S
            XgEMACMcVvPcylAT7xddMFgb9eW+3bBPmJebur8yYvbKFi6QUn0yGqUBAjWoBfWf
            v+eL8zOkPEGOxaSgBDdkWj+jleEIY+Xe20sH/FPq7epiXdR/fjbfSAfEh4yo0os=
            =dQIT
            -----END PGP MESSAGE-----
          fp: 0DA051A11F759C7037D0297A494897BF3D123CE3
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
